### ISSUE TITLE
Translation misses punctuation e.g. quotes

### ISSUE THREAD

**Issue by vcvpaiva** [UniversalDependencies/UD_Portuguese-PUD#1]
The first sentence is (in EN):
“While much of the digital transition is unprecedented in the United States, the peaceful transition of power is not,” Obama special assistant Kori Schulman wrote in a blog post Monday.
the translation has no quotes:
Embora uma grande parte da transição digital nos Estados Unidos seja sem precedentes, a transição pacífica de poder não o é, escreveu Kori Schulman, assistente especial de Obama, numa publicação no blog, na segunda-feira.

**Comment by vcvpaiva** [comment]
another one of these:

 sent_id = n01092040

 text = Estamos ativamente à procura de formas possíveis de limitar o âmbito do litígio para apenas aqueles que tenham uma posição real no projeto, foi citado.

 text_en = “We are actively thinking of possible ways to limit the scope of litigation to only those with a real standing in a project,” he was quoted as saying.

**Comment by vcvpaiva** [comment]
Without the quotation marks, the sentences become much harder to understand.

Also bad translation on the second one, it should be
"Estamos ativamente à procura de formas possíveis de limitar o âmbito do litígio para apenas aqueles que tenham uma posição real no projeto",  ele foi citado como dizendo sobre o caso.

**Comment by arademaker** [comment]
For the sentence n01092040, I would be in favor of the following translation:

> "Estamos ativamente pensando em possíveis formas de limitar o âmbito do litígio para apenas aqueles que tenham uma posição real no projeto", ele foi citado como dizendo.

Note the use of `pensando` verb to keep the original structure of the sentence
