### ISSUE TITLE
subordinate conjunctions

### ISSUE THREAD

**Issue by vcvpaiva** [UniversalDependencies/UD_Portuguese-PUD#10]
the stats shows  PT has NO subordinate conjunctions, which is crazy, as EN has 290 of them!
some examples that I'm sure would be SCONJ in PT too:

estimates that==>estima que

told police that==>contou à polícia que

he felt that ==>ele sentiu que [deviam abandonar o edifício]

(we need a good open dictionary of valences for PT!)

**Comment by vcvpaiva** [comment]
but to be less wrong whenever we have a line like
>sentiu	_	VERB	VBC	Aspect=Perf|Mood=Ind|Number=Sing|Person=3|Tense=Past	3	acl:relcl	_	_
>	que	_	ADP	IN	_	16	mark	_	_

with VERB and ending with acl:relcl,  the next line "que" should be SCONJ.

**Comment by dan-zeman** [comment]
Why is `acl:relcl` important, or even related in any way?

**Comment by vcvpaiva** [comment]
because it means that a relative clause is introduced by the subordinate conjunction.

it does not get all subordinate conjunctions, but I expect that everything it gets is a subordinate conjunction. these should be the easier ones.

**Comment by dan-zeman** [comment]
But if the deprel `acl:relcl` appears at the verb _before_ the conjunction, it is not the verb within the clause introduced by the conjunction (instead, it is probably the verb to which the following clause is attached) and it is irrelevant whether it is attached to its own parent as `acl:relcl`, `acl`, `advcl`, `root` or anything else.

I would also argue that if a clause is introduced by a subordinating conjunction, it is a subordinate clause but not a relative clause. If it is a relative clause, then _que_ is not a conjunction but a pronoun. Something like the following (pardong Google Translate if the sentence is incorrect): _o homem que veio ontem_ "the man who came yesterday".

Nevertheless, I agree that if _que_ is tagged `ADP` and attached via the `mark` relation, it is likely that it should actually be tagged `SCONJ`.

**Comment by vcvpaiva** [comment]
ok, I don't know how these things really work, you know best.

but I know that of all the examples that had SCONJ in English, some are of the type that introduces a new independent clause and these are different from "o homem que veio ontem" (perfectly fine sentence, but not an independent clause).

**Comment by vcvpaiva** [comment]
Examples that I believe are SCONJ:

1. proclaim that==>anunciou que
 newdoc id = n01002
 sent_id = n01002017
 text = Mas numa pausa da sua retórica passada acerca da restrição da imigração, o nomeado da GOP anunciou que, como presidente, ele iria permitir "números tremendos" de imigrantes legais, baseado num "sistema de mérito".
 text_en = But in a break from his past rhetoric about curtailing immigration, the GOP nominee proclaimed that as president he would allow “tremendous numbers” of legal immigrants based on a “merit system.”

2. estimates that==> estima que
sent_id = n01005031
 text = O estudo de viabilidade estima que os passageiros iriam levar quatro minutos para atravessar o Rio Potomac na gôndola.
 text_en = The feasibility study estimates that it would take passengers about four minutes to cross the Potomac River on the gondola.

3. told Police that==>contou a policia que
 newdoc id = n01006
 sent_id = n01006011
 text = Uma testemunha contou à polícia que a vítima tinha atacado o suspeito em abril.
 text_en = A witness told police that the victim had attacked the suspect in April.

4. felt that==>sentiu que
 newdoc id = n01010
sent_id = n01010042
text = Houve um tempo, disse o Sr. Panvalkar, em que ele sentiu que deviam abandonar o edifício.
text_en = There was a time, Mr Panvalkar said, when he felt that they should leave the building.

5. it may be that==>pode ser que
 sent_id = n01017008
 text = Mas pode ser que a BA e a IAG o tenham descoberto e possam oferecer algo vagamente confiável.
 text_en = "But it may be that BA and IAG have cracked it and can offer something vaguely reliable."

6. revelaram que==> revealed that
 sent_id = n01021012
 text = As análises revelaram que quantidades históricas de informação foram utilizadas para causar a ruptura.
 text_en = Analysis revealed that historic amounts of data had been used to cause the disruption.

7. say that==>dizem que
 sent_id = n01022005
 text = Muitos cientistas dizem que a tecnologia para remover carbono do ar será agora necessária para atingir os objetivos de Paris.
 text_en = Many scientists say that technology to remove carbon from the air will now be needed to meet the Paris 
targets.

8. fantastic that==> fantástico que
 sent_id = n01022027
 text = É fantástico que eles tenham conseguido o Acordo de Paris, mas as suas contribuições no momento não estão nem perto do objectivo de 1.5 grau.
 text_en = It's fantastic that they got the Paris Agreement but their contributions at the moment are nowhere near the 1.5-degree target.

9. ensure that==>garantir que
 newdoc id = n01034
sent_id = n01034033
 text = Se o Donald Trump se tornar presidente, o governo daqui ainda terá de trabalhar com ele para avançar com alguma agenda partilhada que exista, para garantir que os negócios e os interesses canadenses estão representados em Washington.
 text_en = "If Donald Trump becomes president, the government here will still have to work with him to advance whatever shared agenda there is, to ensure that Canadian businesses and interests are represented in Washington."

10.  charging that=> reforçando que
newdoc id = n01039
 sent_id = n01039013
 text = Clinton e aliados, nesse meio de tempo, estão procurando manter o foco em Trump, reforçando que seus comentários depreciativos sobre mulheres e minorias, e o seu temperamento, o tornam inadequado para a função.
 text_en = Clinton and allies, meanwhile, are seeking to keep the spotlight on Trump, charging that his disparaging comments about women and minorities, and his temperament make him unfit for office.

11. mostrou que=> pointed out that
 sent_id = n01046057
 text = Ele também mostrou que Rogers introduziu, recentemente, um novo app que ajuda os clientes a monitorizar o seu uso de dados.
 text_en = He also pointed out that Rogers recently introduced a new app tool that helps customers monitor their data usage.

12. acknowledged that => reconheceu que
newdoc id = n01060
 sent_id = n01060069
 text = E, admitiu ela, "vocês têm de olhar para onde ela reconheceu que nós precisamos de alguma coisa diferente - nós podemos fazer melhor - e onde ela expressou pesar.
 text_en = And, she granted, “you have to look at where she has acknowledged that we need to do something different—we can do better—and where she has expressed regret.”

13.  understand that=> entendo que
newdoc id = n01078
 sent_id = n01078025
 text = Claro, eu entendo que a Alemanha dos dias modernos deve ser separada do regime Nazi.
 text_en = Of course, I do understand that modern-day Germany must be separated from the Nazi regime.

14. say that=> dizer que
newdoc id = n01087
 sent_id = n01087005
 text = É justo dizer que Rocco Catalano trabalha, vive e respira retro.
 text_en = It’s fair to say that Rocco Catalano works, lives and breathes retro.

15. suggest that==> sugiro que
 newdoc id = n01088
 sent_id = n01088026
 text = Mas, quando eu sugiro que ela use a Frank como sua modelo, ela ri.
 text_en = But, when I suggest that she get Frank to model for her, she laughs.

1	


NB: not of the ones that I wanted to track, but supporting Dan's rule
newdoc id = n01034
sent_id = n01034033
 text = Se o Donald Trump se tornar presidente, o governo daqui ainda terá de trabalhar com ele para avançar com alguma agenda partilhada que exista, para garantir que os negócios e os interesses canadenses estão representados em Washington.
 text_en = "If Donald Trump becomes president, the government here will still have to work with him to advance whatever shared agenda there is, to ensure that Canadian businesses and interests are represented in Washington."

"Se" is a SCONJ par excellence but it's considered ADP mark

**Comment by dan-zeman** [comment]
Thanks, Valeria. It looks like a systematic error: all subordinating conjunctions are tagged as prepositions. It could be used by the English XPOS tag `IN`, which covers both and which seems to be used by the Google folks who prepared this data.

**Comment by dan-zeman** [comment]
Fixed in 7c7d4ab15dfd66f02132830c7cc77793cb3d04ba.
