### ISSUE TITLE
interjection, please

### ISSUE THREAD

**Issue by vcvpaiva** [UniversalDependencies/UD_Portuguese-PUD#15]
the only interjection in the English PUD "hey", corresponds to "Olá" which should be also an interjection

 newdoc id = n01028
 sent_id = n01028022
 text = Felizmente, alguém na Sony Austrália estava do tipo, 'Olá, por falar nisso, vocês repararam?' diz Pall.
 text_en = "Luckily, someone in Sony Australia was like, 'Hey, by the way, did you guys notice this?'" says Pall.
1	Felizmente	_	ADV	RB	_	8	advmod	_	SpaceAfter=No
2	,	_	PUNCT	,	_	1	punct	_	_
3	alguém	_	NOUN	NN	Gender=Masc|Number=Sing	8	nsubj	_	_
4-5	na	_	_	_	_	_	_	_	_
4	em	em	ADP	INDT	_	6	case	_	_
5	a	o	DET	_	Gender=Fem|Number=Sing	6	det	_	_
6	Sony	_	PROPN	NNP	Gender=Fem|Number=Sing	3	nmod	_	_
7	Austrália	_	PROPN	NNP	Gender=Fem|Number=Sing	6	appos	_	_
8	estava	_	VERB	VBC	Aspect=Imp|Mood=Ind|Number=Sing|Person=3|Tense=Past	0	root	_	_
9-10	do	_	_	_	_	_	_	_	_
9	de	de	ADP	INDT	_	11	case	_	_
10	o	o	DET	_	Gender=Masc|Number=Sing	11	det	_	_
11	tipo	_	NOUN	NN	Gender=Masc|Number=Sing	8	obl	_	SpaceAfter=No
12	,	_	PUNCT	,	_	22	punct	_	_
13	'	_	PUNCT	``	_	22	punct	_	SpaceAfter=No
14	Olá	_	X	UH	_	22	discourse	_	SpaceAfter=No
15	,	_	PUNCT	,	_	14	punct	_	_
16	por	_	ADP	IN	_	18	case	_	_
17	falar	_	VERB	VB	_	18	case	_	_
18-19	nisso	_	_	_	_	_	_	_	SpaceAfter=No
18	em	em	ADP	INPDEM	_	22	obl	_	_
19	isso	este	DET	_	Gender=Masc|Number=Sing	18	det	_	_
20	,	_	PUNCT	,	_	18	punct	_	_
21	vocês	_	PRON	PRP	Case=Nom|Number=Plur|Person=3	22	nsubj	_	_
22	repararam	_	VERB	VBC	Aspect=Perf|Mood=Ind|Number=Plur|Person=3|Tense=Past	8	parataxis	_	SpaceAfter=No
23	?	_	PUNCT	.	_	22	punct	_	SpaceAfter=No
24	'	_	PUNCT	''	_	22	punct	_	_
25	diz	_	VERB	VBC	Aspect=Imp|Mood=Ind|Number=Sing|Person=3|Tense=Pres	8	parataxis	_	_
26	Pall	_	PROPN	NNP	Gender=Masc|Number=Sing	25	nsubj	_	SpaceAfter=No
27	.	_	PUNCT	.	_	8	punct	_	_

**Comment by arademaker** [comment]
it was solved by @dan-zeman already.
