### ISSUE TITLE
people's names

### ISSUE THREAD

**Issue by vcvpaiva** [UniversalDependencies/UD_Portuguese-PUD#16]
this seems the wrong way of dealing with the name "Juan Carlos Salas": Salas is NOT a common noun. and the whole name is not a compound.

 sent_id = n01150042
 text = Criado por Juan Carlos Salas, o prédio vencedor tem uma aparência escultural e todos os detalhes têm um significado.
 text_en = Designed by Juan Carlos Salas, the award-winning building has a sculptural appearance and every detail carries meaning.

1	Criado	_	VERB	VBN	Aspect=Perf|Gender=Masc|Number=Sing	8	acl	_	_
2	por	_	ADP	IN	_	3	case	_	_
3	Juan	_	PROPN	NNP	Gender=Masc|Number=Sing	1	obl	_	_
4	Carlos	_	PROPN	NNP	Gender=Masc|Number=Sing	3	flat:name	_	_
5	Salas	_	NOUN	NN	Gender=Fem|Number=Plur	3	compound	_	Proper=True|SpaceAfter=No
6	,	_	PUNCT	,	_	1	punct	_	_
7	o	_	DET	DT	Gender=Masc|Number=Sing	8	det	_	_
8	prédio	_	NOUN	NN	Gender=Masc|Number=Sing	10	nsubj	_	_
9	vencedor	_	ADJ	JJ	Gender=Masc|Number=Sing	8	amod	_	_
10	tem	_	VERB	VBC	Aspect=Imp|Mood=Ind|Number=Sing|Person=3|Tense=Pres	0	root	_	_
11	uma	_	DET	DT	Gender=Fem|Number=Sing	12	det	_	_
12	aparência	_	NOUN	NN	Gender=Fem|Number=Sing	10	obj	_	_
13	escultural	_	ADJ	JJ	Gender=Fem|Number=Sing	12	amod	_	_
14	e	_	CCONJ	CC	_	18	cc	_	_
15	todos	_	DET	PDT	Gender=Masc|Number=Plur	17	det:predet	_	_
16	os	_	DET	DT	Gender=Masc|Number=Plur	17	det	_	_
17	detalhes	_	NOUN	NN	Gender=Masc|Number=Plur	18	nsubj	_	_
18	têm	_	VERB	VBC	Aspect=Imp|Mood=Ind|Number=Plur|Person=3|Tense=Pres	10	conj	_	_
19	um	_	DET	DT	Gender=Masc|Number=Sing	20	det	_	_
20	significado	_	NOUN	NN	Gender=Masc|Number=Sing	18	obj	_	SpaceAfter=No
21	.	_	PUNCT	.	_	10	punct	_	_

**Comment by vcvpaiva** [comment]
this also seems not a good use of compound, but seems more debatable how to deal with a name like "Andre Price III"

 sent_id = n01011011
 text = Ela matou o Andre Price III ao pressionar a cara dele contra um colchão de ar na sua sala de estar, antes de tentar fazer o mesmo à sua filha, Angel, disse a polícia.
 text_en = She killed Andre Price III by pressing his face into an air mattress in her sitting room before trying to do the same to her daughter, Angel, police said.
1	Ela	_	PRON	PRP	Case=Nom|Gender=Fem|Number=Sing|Person=3	2	nsubj	_	_
2	matou	_	VERB	VBC	Aspect=Perf|Mood=Ind|Number=Sing|Person=3|Tense=Past	0	root	_	_
3	o	_	DET	DT	Gender=Masc|Number=Sing	4	det	_	_
4	Andre	_	PROPN	NNP	Gender=Masc|Number=Sing	2	obj	_	_
5	Price	_	PROPN	NNP	Gender=Masc|Number=Sing	4	flat:name	_	_
6	III	_	ADJ	JJ	Gender=Masc|Number=Sing	4	compound	_	Proper=True
7-8	ao	_	_	_	_	_	_	_	_
7	a	a	ADP	INDT	_	9	case	_	_
8	o	o	DET	_	Gender=Masc|Number=Sing	9	det	_	_
9	pressionar	_	VERB	VB	_	2	xcomp	_	_
10	a	_	DET	DT	Gender=Fem|Number=Sing	11	det	_	_
11	cara	_	NOUN	NN	Gender=Fem|Number=Sing	9	obj	_	_
12-13	dele	_	_	_	_	_	_	_	ToDo=pobj
12	de	de	ADP	_	_	13	case	_	_
13	ele	ele	PRON	INP	Gender=Masc|Number=Sing|Person=3	11	obj	_	_
14	contra	_	ADP	IN	_	16	case	_	_
15	um	_	DET	DT	Gender=Masc|Number=Sing	16	det	_	_
16	colchão	_	NOUN	NN	Gender=Masc|Number=Sing	9	obl	_	_
17	de	_	ADP	IN	_	18	case	_	_
18	ar	_	NOUN	NN	Gender=Masc|Number=Sing	16	nmod	_	_
19-20	na	_	_	_	_	_	_	_	_
19	em	em	ADP	INDT	_	22	case	_	_
20	a	o	DET	_	Gender=Fem|Number=Sing	22	det	_	_
21	sua	_	PRON	DTP$	Gender=Fem|Number=Sing|Number[psor]=Sing|Person=3|PronType=Prs	22	det	_	_
22	sala	_	NOUN	NN	Gender=Fem|Number=Sing	9	obl	_	_
23	de	_	ADP	IN	_	24	case	_	_
24	estar	_	NOUN	NN	Gender=Masc|Number=Sing	22	nmod	_	SpaceAfter=No
25	,	_	PUNCT	,	_	26	punct	_	_
26	antes	_	ADV	RB	_	2	advmod	_	_
27	de	_	ADP	IN	_	28	case	_	_
28	tentar	_	VERB	VB	_	26	xcomp	_	_
29	fazer	_	VERB	VB	_	28	xcomp	_	_
30	o	_	DET	DT	Gender=Masc|Number=Sing	31	det	_	_
31	mesmo	_	NOUN	NN	Gender=Masc|Number=Sing	29	obj	_	_
32-33	à	_	_	_	_	_	_	_	_
32	a	a	ADP	INDT	_	35	case	_	_
33	a	o	DET	_	Gender=Fem|Number=Sing	35	det	_	_
34	sua	_	PRON	DTP$	Gender=Fem|Number=Sing|Number[psor]=Sing|Person=3|PronType=Prs	35	det	_	_
35	filha	_	NOUN	NN	Gender=Fem|Number=Sing	31	nmod	_	SpaceAfter=No
36	,	_	PUNCT	,	_	37	punct	_	_
37	Angel	_	PROPN	NNP	Gender=Fem|Number=Sing	35	appos	_	SpaceAfter=No
38	,	_	PUNCT	,	_	37	punct	_	_
39	disse	_	VERB	VBC	Aspect=Perf|Mood=Ind|Number=Sing|Person=3|Tense=Past	2	parataxis	_	_
40	a	_	DET	DT	Gender=Fem|Number=Sing	41	det	_	_
41	polícia	_	NOUN	NN	Gender=Fem|Number=Sing	39	nsubj	_	SpaceAfter=No
42	.	_	PUNCT	.	_	2	punct	_	_

**Comment by vcvpaiva** [comment]
'Tom Robinson' shouldn't be a compound.

 newdoc id = w01130
 sent_id = w01130099
 text = Rafferty lançou mais dois álbuns na década de 1990 naquilo que o músico Tom Robinson descreveu mais tarde como "um grande retorno à forma".
 text_en = Rafferty released two further albums in the 1990s in what musician Tom Robinson later described as "a major return to form".

1	Rafferty	_	PROPN	NNP	Gender=Masc|Number=Sing	2	nsubj	_	_
2	lançou	_	VERB	VBC	Aspect=Perf|Mood=Ind|Number=Sing|Person=3|Tense=Past	0	root	_	_
3	mais	_	ADJ	JJR	Gender=Masc|Number=Plur	5	amod	_	_
4	dois	_	NUM	CD	Gender=Masc	5	nummod	_	_
5	álbuns	_	NOUN	NN	Gender=Masc|Number=Plur	2	obj	_	_
6-7	na	_	_	_	_	_	_	_	_
6	em	em	ADP	INDT	_	8	case	_	_
7	a	o	DET	_	Gender=Fem|Number=Sing	8	det	_	_
8	década	_	NOUN	NN	Gender=Fem|Number=Sing	2	obl	_	_
9	de	_	ADP	IN	_	10	case	_	_
10	1990	_	NUM	CD	Gender=Masc	8	nmod	_	_
11	naquilo	_	ADP	INPDEM	Gender=Masc|Number=Sing	2	obj	_	ToDo=pobj
12	que	_	PRON	WP	_	17	obj	_	_
13	o	_	DET	DT	Gender=Masc|Number=Sing	14	det	_	_
14	músico	_	NOUN	NN	Gender=Masc|Number=Sing	17	nsubj	_	_
15	Tom	_	NOUN	NN	Gender=Masc|Number=Sing	14	appos	_	Proper=True
16	Robinson	_	PROPN	NNP	Gender=Masc|Number=Sing	15	compound	_	_
17	descreveu	_	VERB	VBC	Aspect=Perf|Mood=Ind|Number=Sing|Person=3|Tense=Past	11	acl:relcl	_	_
18	mais	_	ADV	RBR	_	19	advmod	_	_
19	tarde	_	ADV	RB	_	17	advmod	_	_
20	como	_	ADP	IN	_	24	case	_	_
21	"	_	PUNCT	``	_	24	punct	_	SpaceAfter=No
22	um	_	DET	DT	Gender=Masc|Number=Sing	24	det	_	_
23	grande	_	ADJ	JJ	Gender=Masc|Number=Sing	24	amod	_	_
24	retorno	_	NOUN	NN	Gender=Masc|Number=Sing	17	obl	_	_
25-26	à	_	_	_	_	_	_	_	_
25	a	a	ADP	INDT	_	27	case	_	_
26	a	o	DET	_	Gender=Fem|Number=Sing	27	det	_	_
27	forma	_	NOUN	NN	Gender=Fem|Number=Sing	24	nmod	_	SpaceAfter=No
28	"	_	PUNCT	''	_	24	punct	_	SpaceAfter=No
29	.	_	PUNCT	.	_	2	punct	_	_

**Comment by vcvpaiva** [comment]
the same for Norma Talmadge in

 sent_id = w01136074
 text = Joseph Schenck estava interessado em selecionar a sua esposa, Norma Talmadge, para contracenar comValentino em uma versão de Romeu e Julieta.
 text_en = Joseph Schenck was interested in casting his wife, Norma Talmadge, opposite Valentino in a version of Romeo and Juliet.
1	Joseph	_	PROPN	NNP	Gender=Masc|Number=Sing	4	nsubj	_	_
2	Schenck	_	PROPN	NNP	Gender=Masc|Number=Sing	1	flat:name	_	_
3	estava	_	VERB	VBC	Aspect=Imp|Mood=Ind|Number=Sing|Person=3|Tense=Past	4	aux	_	_
4	interessado	_	VERB	VBN	Aspect=Perf|Gender=Masc|Number=Sing	0	root	_	_
5	em	_	ADP	IN	_	6	case	_	_
6	selecionar	_	VERB	VB	_	4	xcomp	_	_
7	a	_	DET	PDT	Gender=Fem|Number=Sing	9	det:predet	_	_
8	sua	_	PRON	DTP$	Gender=Fem|Number=Sing|Number[psor]=Sing|Person=3|PronType=Prs	9	det	_	_
9	esposa	_	NOUN	NN	Gender=Fem|Number=Sing	6	obj	_	SpaceAfter=No
10	,	_	PUNCT	,	_	11	punct	_	_
11	Norma	_	NOUN	NN	Gender=Fem|Number=Sing	9	appos	_	Proper=True
12	Talmadge	_	PROPN	NNP	Gender=Fem|Number=Sing	11	compound	_	SpaceAfter=No
13	,	_	PUNCT	,	_	11	punct	_	_
14	para	_	ADP	IN	_	15	case	_	_
15	contracenar	_	VERB	VB	_	6	xcomp	_	_
16	com	_	ADP	IN	_	17	case	_	SpaceAfter=No
17	Valentino	_	PROPN	NNP	Gender=Masc|Number=Sing	15	obl	_	_
18	em	_	ADP	IN	_	20	case	_	_
19	uma	_	DET	DT	Gender=Fem|Number=Sing	20	det	_	_
20	versão	_	NOUN	NN	Gender=Fem|Number=Sing	15	obl	_	_
21	de	_	ADP	IN	_	22	case	_	_
22	Romeu	_	PROPN	NNP	Gender=Masc|Number=Sing	20	nmod	_	_
23	e	_	CCONJ	CC	_	24	cc	_	_
24	Julieta	_	PROPN	NNP	Gender=Fem|Number=Sing	22	conj	_	SpaceAfter=No
25	.	_	PUNCT	.	_	4	punct	_	_

**Comment by dan-zeman** [comment]
Apparently the text was pre-tagged automatically and the human annotators did not catch all the errors. Personal names definitely should be `PROPN` regardless whether they look like a common noun in the host language.

The _III_ in _Andre Price III_ is debatable but `compound` is wrong. Either it is `PROPN` and attached via `flat(:name)` to _Andre_. Or it is `ADJ` (ordinal Roman numeral) and attached to _Andre_ as an `amod`.

**Comment by vcvpaiva** [comment]
another one personal name

 newdoc id = n02076
 sent_id = n02076003
 text = Adnan Z. Amin, Diretor Geral da Agência Internacional de Energias Renováveis (IRENA) está seguro: "Energia eólica offshore pode se tornar a maior geradora de energia, em uma economia global, que é livre de energia a base de carvão."
 text_en = Adnan Z. Amin, General Director of the International Organization for Renewable Energies (IRENA) is certain: "Offshore wind power can become the top power generator in a global economy that is free of coal-based energy."
1	Adnan	_	PROPN	NNP	Gender=Masc|Number=Sing	18	nsubj	_	_
2	Z.	_	NOUN	NN	Gender=Masc|Number=Sing	1	compound	_	Proper=True
3	Amin	_	PROPN	NNP	Gender=Masc|Number=Sing	1	flat:name	_	SpaceAfter=No
4	,	_	PUNCT	,	_	5	punct	_	_
5	Diretor	_	NOUN	NN	Gender=Masc|Number=Sing	1	appos	_	_
6	Geral	_	ADJ	JJ	Gender=Masc|Number=Sing	5	amod	_	_
7-8	da	_	_	_	_	_	_	_	_
7	de	de	ADP	INDT	_	9	case	_	_
8	a	o	DET	_	Gender=Fem|Number=Sing	9	det	_	_
9	Agência	_	NOUN	NN	Gender=Fem|Number=Sing	5	nmod	_	Proper=True
10	Internacional	_	ADJ	JJ	Gender=Fem|Number=Sing	9	amod	_	Proper=True
11	de	_	ADP	IN	_	12	case	_	Proper=True
12	Energias	_	NOUN	NN	Gender=Fem|Number=Plur	9	nmod	_	Proper=True
13	Renováveis	_	ADJ	JJ	Gender=Fem|Number=Plur	12	amod	_	Proper=True
14	(	_	PUNCT	(	_	15	punct	_	SpaceAfter=No
15	IRENA	_	PROPN	NNP	Gender=Fem|Number=Sing	9	appos	_	SpaceAfter=No
16	)	_	PUNCT	)	_	15	punct	_	_
17	está	_	AUX	VBC	Aspect=Imp|Mood=Ind|Number=Sing|Person=3|Tense=Pres	18	cop	_	_
18	seguro	_	ADJ	JJ	Gender=Masc|Number=Sing	0	root	_	SpaceAfter=No
19	:	_	PUNCT	:	_	29	punct	_	_
20	"	_	PUNCT	``	_	29	punct	_	SpaceAfter=No
21	Energia	_	NOUN	NN	Gender=Fem|Number=Sing	29	nsubj:pass	_	_
22	eólica	_	ADJ	JJ	Gender=Fem|Number=Sing	21	amod	_	_
23	offshore	_	ADJ	JJ	Gender=Fem|Number=Sing	21	amod	_	_
24	pode	_	VERB	VBC	Aspect=Imp|Mood=Ind|Number=Sing|Person=3|Tense=Pres	29	aux	_	_
25	se	_	PRON	SE	Person=3	29	compound:prt	_	_
26	tornar	_	AUX	VB	_	29	cop	_	_
27	a	_	DET	DT	Gender=Fem|Number=Sing	29	det	_	_
28	maior	_	ADJ	JJS	Gender=Fem|Number=Sing	29	amod	_	_
29	geradora	_	NOUN	NN	Gender=Fem|Number=Sing	18	parataxis	_	_
30	de	_	ADP	IN	_	31	case	_	_
31	energia	_	NOUN	NN	Gender=Fem|Number=Sing	29	nmod	_	SpaceAfter=No|ToDo=nmod
32	,	_	PUNCT	,	_	35	punct	_	_
33	em	_	ADP	IN	_	35	case	_	_
34	uma	_	DET	DT	Gender=Fem|Number=Sing	35	det	_	_
35	economia	_	NOUN	NN	Gender=Fem|Number=Sing	29	nmod	_	ToDo=nmod
36	global	_	ADJ	JJ	Gender=Fem|Number=Sing	35	amod	_	SpaceAfter=No
37	,	_	PUNCT	,	_	40	punct	_	_
38	que	_	PRON	WP	_	40	nsubj	_	_
39	é	_	AUX	VBC	Aspect=Imp|Mood=Ind|Number=Sing|Person=3|Tense=Pres	40	cop	_	_
40	livre	_	ADJ	JJ	Gender=Fem|Number=Sing	35	acl:relcl	_	_
41	de	_	ADP	IN	_	42	case	_	_
42	energia	_	NOUN	NN	Gender=Fem|Number=Sing	40	obl	_	_
43	a	_	ADP	INDT	Gender=Fem|Number=Sing	44	case	_	_
44	base	_	NOUN	NN	Gender=Fem|Number=Sing	42	nmod	_	_
45	de	_	ADP	IN	_	46	case	_	_
46	carvão	_	NOUN	NN	Gender=Masc|Number=Sing	44	nmod	_	SpaceAfter=No
47	.	_	PUNCT	.	_	29	punct	_	SpaceAfter=No
48	"	_	PUNCT	''	_	29	punct	_	_

**Comment by vcvpaiva** [comment]
`Tina Anselmi' should not be compound in two sentences

 newdoc id = n04001
 sent_id = n04001002
 text = Tina Anselmi nasceu em 25 de março, 1927 em Castelfranco Veneto; ela cresceu em uma família católica anti-fascista, a qual foi marcada por perseguições ao seu pai militante socialista.
 text_en = Tina Anselmi was born on the 25th of March, 1927 in Castelfranco Veneto; she grew up in an anti-fascist Catholic family, which was marked by the persecution of her militant socialist father.
1	Tina	_	NOUN	NN	Gender=Fem|Number=Sing	3	nsubj	_	Proper=True
2	Anselmi	_	PROPN	NNP	Gender=Fem|Number=Sing	1	compound	_	_
3	nasceu	_	VERB	VBC	Aspect=Perf|Mood=Ind|Number=Sing|Person=3|Tense=Past	0	root	_	_
4	em	_	ADP	IN	_	5	case	_	_
5	25	_	NUM	CD	_	3	obl	_	_
6	de	_	ADP	IN	_	7	case	_	_
7	março	_	NOUN	NN	Gender=Masc|Number=Sing	5	nmod	_	SpaceAfter=No
8	,	_	PUNCT	,	_	9	punct	_	_
9	1927	_	NUM	CD	Gender=Masc	7	obl:tmod	_	_
10	em	_	ADP	IN	_	11	case	_	_
11	Castelfranco	_	PROPN	NNP	Gender=Fem|Number=Sing	3	obl	_	_
12	Veneto	_	PROPN	NNP	Foreign=Yes|Gender=Fem|Number=Sing	11	flat	_	SpaceAfter=No
13	;	_	PUNCT	,	_	15	punct	_	_
14	ela	_	PRON	PRP	Case=Nom|Gender=Fem|Number=Sing|Person=3	15	nsubj	_	_
15	cresceu	_	VERB	VBC	Aspect=Perf|Mood=Ind|Number=Sing|Person=3|Tense=Past	3	parataxis	_	_
16	em	_	ADP	IN	_	18	case	_	_
17	uma	_	DET	DT	Gender=Fem|Number=Sing	18	det	_	_
18	família	_	NOUN	NN	Gender=Fem|Number=Sing	15	obl	_	_
19	católica	_	ADJ	JJ	Gender=Fem|Number=Sing	18	amod	_	_
20	anti-fascista	_	ADJ	JJ	Gender=Fem|Number=Sing	18	amod	_	SpaceAfter=No
21	,	_	PUNCT	,	_	25	punct	_	_
22	a	_	DET	DT	Gender=Fem|Number=Sing	23	det	_	_
23	qual	_	PRON	WP	Number=Sing	25	nsubj:pass	_	_
24	foi	_	VERB	VBC	Aspect=Perf|Mood=Ind|Number=Sing|Person=3|Tense=Past	25	aux:pass	_	_
25	marcada	_	VERB	VBN	Aspect=Perf|Gender=Fem|Number=Sing	18	acl:relcl	_	_
26	por	_	ADP	IN	_	27	case	_	_
27	perseguições	_	NOUN	NN	Gender=Fem|Number=Plur	25	obl	_	_
28-29	ao	_	_	_	_	_	_	_	_
28	a	a	ADP	INDT	_	31	case	_	_
29	o	o	DET	_	Gender=Masc|Number=Sing	31	det	_	_
30	seu	_	PRON	DTP$	Gender=Masc|Number=Sing|Number[psor]=Sing|Person=3|PronType=Prs	31	det	_	_
31	pai	_	NOUN	NN	Gender=Masc|Number=Sing	27	nmod	_	_
32	militante	_	ADJ	JJ	Gender=Masc|Number=Sing	31	amod	_	_
33	socialista	_	ADJ	JJ	Gender=Masc|Number=Sing	31	amod	_	SpaceAfter=No
34	.	_	PUNCT	.	_	3	punct	_	_

and 

sent_id = n04001013
 text = Tendo sempre sido próxima da União Católica, Tina Anselmi ocupava-se particularmente dos direitos dos trabalhadores têxteis e professores.
 text_en = Having always been close to the Catholic Union, Tina Anselmi attended particularly to the rights of textile workers and teachers.

**Comment by vcvpaiva** [comment]
another 2 names (Cristina Cifuentes and Javier Maroto)  that shouldn't be compound. Maroto is not ADJ but PROPN

 newdoc id = n05001
 sent_id = n05001005
 text = A presidente da Comunidade de Madrid, Cristina Cifuentes, representa os mais conservadores, enquanto líderes do partido, como o Subsecretário Setorial Javier maroto, representa os mais progressivos.
 text_en = The president of the Community of Madrid, Cristina Cifuentes, represents the most conservative, while leaders of the party, such as the Sectorial Under-Secretary, Javier Maroto, represent the most progressive.
1	A	_	DET	DT	Gender=Fem|Number=Sing	2	det	_	_
2	presidente	_	NOUN	NN	Gender=Fem|Number=Sing	12	nsubj	_	_
3-4	da	_	_	_	_	_	_	_	_
3	de	de	ADP	INDT	_	5	case	_	_
4	a	o	DET	_	Gender=Fem|Number=Sing	5	det	_	_
5	Comunidade	_	NOUN	NN	Gender=Fem|Number=Sing	2	nmod	_	Proper=True
6	de	_	ADP	IN	_	7	case	_	Proper=True
7	Madrid	_	PROPN	NNP	Gender=Fem|Number=Sing	5	nmod	_	SpaceAfter=No
8	,	_	PUNCT	,	_	9	punct	_	_
9	Cristina	_	PROPN	NNP	Gender=Fem|Number=Sing	2	appos	_	_
10	Cifuentes	_	NOUN	NN	Gender=Fem|Number=Sing	9	compound	_	Proper=True|SpaceAfter=No
11	,	_	PUNCT	,	_	9	punct	_	_
12	representa	_	VERB	VBC	Aspect=Imp|Mood=Ind|Number=Sing|Person=3|Tense=Pres	0	root	_	_
13	os	_	DET	DT	Gender=Masc|Number=Plur	15	det	_	_
14	mais	_	ADJ	JJS	Gender=Masc|Number=Plur	15	amod	_	_
15	conservadores	_	NOUN	NN	Gender=Masc|Number=Plur	12	obj	_	SpaceAfter=No
16	,	_	PUNCT	,	_	30	punct	_	_
17	enquanto	_	ADP	IN	_	30	mark	_	_
18	líderes	_	NOUN	NN	Gender=Masc|Number=Plur	30	nsubj	_	_
19-20	do	_	_	_	_	_	_	_	_
19	de	de	ADP	INDT	_	21	case	_	_
20	o	o	DET	_	Gender=Masc|Number=Sing	21	det	_	_
21	partido	_	NOUN	NN	Gender=Masc|Number=Sing	18	nmod	_	SpaceAfter=No
22	,	_	PUNCT	,	_	25	punct	_	_
23	como	_	ADP	IN	_	25	case	_	_
24	o	_	DET	DT	Gender=Masc|Number=Sing	25	det	_	_
25	Subsecretário	_	NOUN	NN	Gender=Masc|Number=Sing	18	nmod	_	_
26	Setorial	_	ADJ	JJ	Gender=Masc|Number=Sing	25	amod	_	_
27	Javier	_	PROPN	NNP	Gender=Masc|Number=Sing	25	appos	_	_
28	maroto	_	ADJ	JJ	Gender=Masc|Number=Sing	27	compound	_	Proper=True|SpaceAfter=No
29	,	_	PUNCT	,	_	25	punct	_	_
30	representa	_	VERB	VBC	Aspect=Imp|Mood=Ind|Number=Plur|Person=3|Tense=Pres	12	advcl	_	_
31	os	_	DET	DT	Gender=Masc|Number=Plur	33	det	_	_
32	mais	_	ADJ	JJS	Gender=Masc|Number=Plur	33	amod	_	_
33	progressivos	_	NOUN	NN	Gender=Masc|Number=Plur	30	obj	_	SpaceAfter=No
34	.	_	PUNCT	.	_	12	punct	_	_

**Comment by vcvpaiva** [comment]
Pintado is the name of the person, not an adjective

 sent_id = n05001008
 text = Durán atua como porta-voz e Ángel Pintado como ministro da fazenda.
 text_en = Durán acts as spokesman and Ángel Pintado as treasurer.
1	Durán	_	PROPN	NNP	Gender=Masc|Number=Sing	2	nsubj	_	_
2	atua	_	VERB	VBC	Aspect=Imp|Mood=Ind|Number=Sing|Person=3|Tense=Pres	0	root	_	_
3	como	_	ADP	IN	_	4	case	_	_
4	porta-voz	_	NOUN	NN	Gender=Masc|Number=Sing	2	obl	_	_
5	e	_	CCONJ	CC	_	6	cc	_	_
6	Ángel	_	PROPN	NNP	Gender=Masc|Number=Sing	2	conj	_	orig_deprel=nsubj
7	Pintado	_	ADJ	JJ	Gender=Masc|Number=Sing	6	compound	_	Proper=True
8	como	_	ADP	IN	_	6	orphan	_	orig_deprel=obl|ToDo=ex-adp-child
9	ministro	_	NOUN	NN	Gender=Masc|Number=Sing	8	obj	_	Proper=True|ToDo=pobj
10-11	da	_	_	_	_	_	_	_	Proper=True
10	de	de	ADP	INDT	_	12	case	_	_
11	a	o	DET	_	Gender=Fem|Number=Sing	12	det	_	_
12	fazenda	_	NOUN	NN	Gender=Fem|Number=Sing	9	nmod	_	Proper=True|SpaceAfter=No
13	.	_	PUNCT	.	_	2	punct	_	_

**Comment by vcvpaiva** [comment]
Like the _III_ in _Andre Price III_  and several kings we have Jr in

 sent_id = w02005029
 text = Possui um monumento a Martin Luther King Jr.
 text_en = It contains a monument to Martin Luther King, Jr.

1	Possui	_	VERB	VBC	Aspect=Imp|Mood=Ind|Number=Sing|Person=3|Tense=Pres	0	root	_	_
2	um	_	DET	DT	Gender=Masc|Number=Sing	3	det	_	_
3	monumento	_	NOUN	NN	Gender=Masc|Number=Sing	1	obj	_	_
4	a	_	ADP	IN	_	5	case	_	_
5	Martin	_	PROPN	NNP	Gender=Masc|Number=Sing	3	nmod	_	_
6	Luther	_	PROPN	NNP	Gender=Masc|Number=Sing	5	flat:name	_	_
7	King	_	PROPN	NNP	Gender=Masc|Number=Sing	5	flat:name	_	_
8	Jr	_	ADJ	JJ	Gender=Masc|Number=Sing	5	compound	_	Proper=True|SpaceAfter=No
9	.	_	PUNCT	.	_	1	punct	_	_

**Comment by vcvpaiva** [comment]
another first name only (and very bad translation of 'who', it should be 'que' not 'quem')

 sent_id = w05010025
 text = Enquanto isso, seu lugar na tribuna foi tomado por Marco Antonio, quem ocupou a posição até dezembro.
 text_en = Meanwhile, his place in tribune was occupied by Marco Antonio, who held the position until December.

1	Enquanto	_	ADP	IN	_	10	discourse	_	_
2	isso	_	PRON	PDEM	Gender=Masc|Number=Sing	1	fixed	_	SpaceAfter=No
3	,	_	PUNCT	,	_	1	punct	_	_
4	seu	_	PRON	DTP$	Gender=Masc|Number=Sing|Number[psor]=Sing|Person=3|PronType=Prs	5	det	_	_
5	lugar	_	NOUN	NN	Gender=Masc|Number=Sing	10	nsubj:pass	_	_
6-7	na	_	_	_	_	_	_	_	_
6	em	em	ADP	INDT	_	8	case	_	_
7	a	o	DET	_	Gender=Fem|Number=Sing	8	det	_	_
8	tribuna	_	NOUN	NN	Gender=Fem|Number=Sing	5	nmod	_	_
9	foi	_	VERB	VBC	Aspect=Perf|Mood=Ind|Number=Sing|Person=3|Tense=Past	10	aux:pass	_	_
10	tomado	_	VERB	VBN	Aspect=Perf|Gender=Masc|Number=Sing	0	root	_	_
11	por	_	ADP	IN	_	12	case	_	_
12	Marco	_	NOUN	NN	Gender=Masc|Number=Sing	10	obl	_	Proper=True
13	Antonio	_	PROPN	NNP	Gender=Masc|Number=Sing	12	compound	_	SpaceAfter=No
14	,	_	PUNCT	,	_	16	punct	_	_
15	quem	_	PRON	WP	_	16	nsubj	_	_
16	ocupou	_	VERB	VBC	Aspect=Perf|Mood=Ind|Number=Sing|Person=3|Tense=Past	12	acl:relcl	_	_
17	a	_	DET	DT	Gender=Fem|Number=Sing	18	det	_	_
18	posição	_	NOUN	NN	Gender=Fem|Number=Sing	16	obj	_	_
19	até	_	ADP	IN	_	20	case	_	_
20	dezembro	_	NOUN	NN	Gender=Masc|Number=Sing	16	obl	_	SpaceAfter=No
21	.	_	PUNCT	.	_	10	punct	_	_

**Comment by vcvpaiva** [comment]
last person name considered "compound" Marco Antônio

 sent_id = w05010027
 text = Em 1.º de janeiro, 49 a.C., Marco Antônio leu uma declaração de César, na qual o pro-cônsul declarou-se um amigo da paz.
 text_en = On the 1st January 49 BC, Marco Antonio read a declaration from Caesar in which the proconsul declared himself a friend of peace.
1	Em	_	ADP	IN	_	2	case	_	_
2	1.º	_	ADJ	JJ	Gender=Masc|Number=Sing	11	obl	_	_
3	de	_	ADP	IN	_	4	case	_	_
4	janeiro	_	NOUN	NN	Gender=Masc|Number=Sing	2	nmod	_	SpaceAfter=No|ToDo=nmod
5	,	_	PUNCT	,	_	6	punct	_	_
6	49	_	NUM	CD	_	4	obl:tmod	_	_
7	a.C.	_	NOUN	NN	Gender=Masc|Number=Sing	6	advmod	_	OrigForm=aC|SpaceAfter=No
8	,	_	PUNCT	,	_	6	punct	_	_
9	Marco	_	NOUN	NN	Gender=Masc|Number=Sing	11	nsubj	_	Proper=True
10	Antônio	_	PROPN	NNP	Gender=Masc|Number=Sing	9	compound	_	_
11	leu	_	VERB	VBC	Aspect=Perf|Mood=Ind|Number=Sing|Person=3|Tense=Past	0	root	_	_
12	uma	_	DET	DT	Gender=Fem|Number=Sing	13	det	_	_
13	declaração	_	NOUN	NN	Gender=Fem|Number=Sing	11	obj	_	_
14	de	_	ADP	IN	_	15	case	_	_
15	César	_	PROPN	NNP	Gender=Masc|Number=Sing	13	nmod	_	SpaceAfter=No
16	,	_	PUNCT	,	_	26	punct	_	_
17-18	na	_	_	_	_	_	_	_	_
17	em	em	ADP	INDT	_	19	case	_	_
18	a	o	DET	_	Gender=Fem|Number=Sing	19	det	_	_
19	qual	_	PRON	WP	Number=Sing	26	nmod	_	ToDo=nmod
20	o	_	DET	DT	Gender=Masc|Number=Sing	21	det	_	_
21	pro-cônsul	_	NOUN	NN	Gender=Masc|Number=Sing	26	nsubj	_	_
22	declarou	_	AUX	VBC	Aspect=Perf|Mood=Ind|Number=Sing|Person=3|Tense=Past	26	cop	_	SpaceAfter=No
23	-	_	PUNCT	-	_	22	punct	_	SpaceAfter=No
24	se	_	PRON	SE	Person=3	26	compound:prt	_	_
25	um	_	DET	DT	Gender=Masc|Number=Sing	26	det	_	_
26	amigo	_	NOUN	NN	Gender=Masc|Number=Sing	13	acl:relcl	_	_
27-28	da	_	_	_	_	_	_	_	_
27	de	de	ADP	INDT	_	29	case	_	_
28	a	o	DET	_	Gender=Fem|Number=Sing	29	det	_	_
29	paz	_	NOUN	NN	Gender=Fem|Number=Sing	26	nmod	_	SpaceAfter=No|ToDo=nmod
30	.	_	PUNCT	.	_	11	punct	_	_

**Comment by arademaker** [comment]
I feel bad for keeping `III` as ADJ in `Andre Price III` but `Jr` as `flat:name` to `... King Jr`...  but I missing a more strong argument to change it.

**Comment by vcvpaiva** [comment]
well, there are all the other kings that I haven't written explicitly yet, e.g. Ramses II, Tutmes III, Amintas I
