### ISSUE TITLE
bad translation: verb 'to oppose'

### ISSUE THREAD

**Issue by vcvpaiva** [UniversalDependencies/UD_Portuguese-PUD#17]
newdoc id = n01032
 sent_id = n01032032
 text = Contudo houve muitos MLASs, com profundas crenças religiosas, que se oposeram à nova legislação.
 text_en = However there are many MLAs with deeply-held religious beliefs who oppose any new legislation.

in PT-BR I think the verb is "se opuseram", I'd say there's no reason for the past tense and "any" is missing.

Contudo há muitos MLASs, com profundas crenças religiosas, que se opõe à qualquer nova legislação.

**Comment by dan-zeman** [comment]
> in PT-BR I think the verb is "se opuseram"

Is this different in Brazilian and European Portuguese? I don't know what the instructions and the background of the translator was, but I think that the translation was done in Europe. (Although it could have been outsourced over the internet of course.)

**Comment by arademaker** [comment]
Commit 1d59c27 solved this issue. Validation didn't report any new error.

**Comment by vcvpaiva** [comment]
> > in PT-BR I think the verb is "se opuseram"
> 
> Is this different in Brazilian and European Portuguese? I don't know what the instructions and the background of the translator was, but I think that the translation was done in Europe. (Although it could have been outsourced over the internet of course.)

@dan-zeman Alexandre checked with Hugo Goncalo, from Coimbra that they also write "opuseram" 
or in this case "opõe".

**Comment by arademaker** [comment]
In that case "opõem" plural
