### ISSUE TITLE
debatable compounds

### ISSUE THREAD

**Issue by vcvpaiva** [UniversalDependencies/UD_Portuguese-PUD#18]
1. Primeira Dama below.

'Dama' is a noun, not X, 'primeira' here seems to me ADJ, not 'noun', the whole thing does not look "compound" at all.

 newdoc id = n01061
 sent_id = n01061016
 text = Mas, à medida que a crítica contra Clinton como Primeira Dama se tornou mais ácida, Karel demonstrou mais empatia.
 text_en = But, as the criticism of Clinton as First Lady became more caustic, Karel became more empathetic.
[..]
12 Primeira	_	NOUN	NN	Gender=Fem|Number=Sing	10	nmod	_	_
13	Dama	_	X	GW	_	12	compound	_	_

2. 'porta voz' in
no compound here, as far as I can see

 sent_id = n01133022
 text = Um porta voz da Harley-Davidson disse que os títulos que têm sobrevoado os meios de comunicação - 2017 ou 2020 - não são precisos.
 text_en = A Harley-Davidson spokeswoman said timelines that have been floated in the media -- 2017 or 2020 -- aren't accurate.
1	Um	_	DET	DT	Gender=Masc|Number=Sing	2	det	_	_
2	porta	_	NOUN	NN	Gender=Masc|Number=Sing	9	nsubj	_	_
3	voz	_	X	GW	_	2	compound	_	_
4-5	da	_	_	_	_	_	_	_	_
4	de	de	ADP	INDT	_	6	case	_	_
5	a	o	DET	_	Gender=Fem|Number=Sing	6	det	_	_
6	Harley	_	PROPN	NNP	Gender=Fem|Number=Sing	2	nmod	_	SpaceAfter=No
7	-	_	PUNCT	-	_	8	punct	_	Proper=True|SpaceAfter=No
8	Davidson	_	PROPN	NNP	Foreign=Yes|Gender=Fem|Number=Sing	6	flat	_	_
9	disse	_	VERB	VBC	Aspect=Perf|Mood=Ind|Number=Sing|Person=3|Tense=Past	0	root	_	_
10	que	_	ADP	IN	_	27	mark	_	_
11	os	_	DET	DT	Gender=Masc|Number=Plur	12	det	_	_
12	títulos	_	NOUN	NN	Gender=Masc|Number=Plur	27	nsubj	_	_
13	que	_	PRON	WP	_	15	nsubj	_	_
14	têm	_	VERB	VBC	Aspect=Imp|Mood=Ind|Number=Plur|Person=3|Tense=Pres	15	aux	_	_
15	sobrevoado	_	VERB	VBN	Aspect=Perf	12	acl:relcl	_	_
16	os	_	DET	DT	Gender=Masc|Number=Plur	17	det	_	_
17	meios	_	NOUN	NN	Gender=Masc|Number=Plur	15	obj	_	_
18	de	_	ADP	IN	_	19	case	_	_
19	comunicação	_	NOUN	NN	Gender=Fem|Number=Sing	17	nmod	_	_
20	-	_	PUNCT	-	_	21	punct	_	_
21	2017	_	NUM	CD	Gender=Masc	12	appos	_	_
22	ou	_	CCONJ	CC	_	23	cc	_	_
23	2020	_	NUM	CD	Gender=Masc	21	conj	_	_
24	-	_	PUNCT	-	_	21	punct	_	_
25	não	_	ADV	RB	Polarity=Neg	27	advmod	_	_
26	são	_	AUX	VBC	Aspect=Imp|Mood=Ind|Number=Plur|Person=3|Tense=Pres	27	cop	_	_
27	precisos	_	ADJ	JJ	Gender=Masc|Number=Plur	9	ccomp	_	SpaceAfter=No
28	.	_	PUNCT	.	_	9	punct	_	_

'voz' is definitely noun, "porta-voz" is a noun ('porta' is the verb 'portar=carry' conjugated), the woman was transformed into a man and "titulos" for timelines is lame!

**Comment by vcvpaiva** [comment]
3. "norte coreano"

 newdoc id = n01143
 sent_id = n01143003
 text = Pair fez uma pegadinha ao entrar no torneio de golfe norte coreano, saiu nas notícias do Brisbane's Nine.
text_en = "Pair prank their way into North Korean golf tournament," read Brisbane's Nine News.

1	Pair	_	PROPN	NNP	Gender=Masc|Number=Sing	2	nsubj	_	_
2	fez	_	VERB	VBC	Aspect=Perf|Mood=Ind|Number=Sing|Person=3|Tense=Past	0	root	_	_
3	uma	_	DET	DT	Gender=Fem|Number=Sing	4	det	_	_
4	pegadinha	_	NOUN	NN	Gender=Fem|Number=Sing	2	obj	_	_
5-6	ao	_	_	_	_	_	_	_	_
5	a	a	ADP	INDT	_	7	case	_	_
6	o	o	DET	_	Gender=Masc|Number=Sing	7	det	_	_
7	entrar	_	VERB	VB	_	2	xcomp	_	_
8-9	no	_	_	_	_	_	_	_	_
8	em	em	ADP	INDT	_	10	case	_	_
9	o	o	DET	_	Gender=Masc|Number=Sing	10	det	_	_
10	torneio	_	NOUN	NN	Gender=Masc|Number=Sing	7	obl	_	_
11	de	_	ADP	IN	_	12	case	_	_
12	golfe	_	NOUN	NN	Gender=Masc|Number=Sing	10	nmod	_	_
13	norte	_	ADJ	JJ	Gender=Masc|Number=Sing	10	amod	_	_
14	coreano	_	X	GW	_	13	compound	_	SpaceAfter=No
15	,	_	PUNCT	,	_	16	punct	_	_
16	saiu	_	VERB	VBC	Aspect=Perf|Mood=Ind|Number=Sing|Person=3|Tense=Past	2	parataxis	_	_
17-18	nas	_	_	_	_	_	_	_	_
17	em	em	ADP	INDT	_	19	case	_	_
18	as	o	DET	_	Gender=Fem|Number=Plur	19	det	_	_
19	notícias	_	NOUN	NN	Gender=Fem|Number=Plur	16	obl	_	_
20-21	do	_	_	_	_	_	_	_	_
20	de	de	ADP	INDT	_	22	case	_	_
21	o	o	DET	_	Gender=Masc|Number=Sing	22	det	_	_
22	Brisbane's	_	PROPN	NNP	Gender=Masc|Number=Sing	19	nmod	_	_
23	Nine	_	PROPN	NNP	Foreign=Yes|Gender=Masc|Number=Sing	22	flat	_	SpaceAfter=No
24	.	_	PUNCT	.	_	2	punct	_	_

this misrepresents the story, there was a pair of Australians, not someone called "Pair".
better translation
"Dupla faz  pegadinha para entrar no torneio de golfe norte coreano," saiu no  Brisbane's Nine News.

norte coreano is ADJ not X!

**Comment by vcvpaiva** [comment]
"bem-sucedidas" in

 sent_id = n01148035
 text = Nem todas as transformações na região têm sido bem sucedidas
 text_en = Not all transformations in the region have been successful.
1	Nem	_	ADV	RB	Polarity=Neg	2	advmod	_	_
2	todas	_	DET	PDT	Gender=Fem|Number=Plur	4	det:predet	_	_
3	as	_	DET	DT	Gender=Fem|Number=Plur	4	det	_	_
4	transformações	_	NOUN	NN	Gender=Fem|Number=Plur	9	nsubj	_	_
5-6	na	_	_	_	_	_	_	_	_
5	em	em	ADP	INDT	_	7	case	_	_
6	a	o	DET	_	Gender=Fem|Number=Sing	7	det	_	_
7	região	_	NOUN	NN	Gender=Fem|Number=Sing	4	nmod	_	_
8	têm	_	VERB	VBC	Aspect=Imp|Mood=Ind|Number=Plur|Person=3|Tense=Pres	9	aux	_	_
9	sido	_	VERB	VBN	Aspect=Perf	0	root	_	_
10	bem	_	ADV	RB	_	9	advmod	_	_
11	sucedidas	_	ADJ	JJ	Gender=Fem|Number=Plur	10	compound	_	_

**Comment by vcvpaiva** [comment]
I've checked (both the French and) the Spanish PUDs.
Primeira Dama/First Lady is not a compound in either.
"portavoz" is written like so in Spanish, so clearly a noun.
Both Spanish and French write a "tournament in North Korea", instead of making it an adjective.

**Comment by vcvpaiva** [comment]
improving my translation:
better translation
"Dupla faz pegadinha para entrar no torneio de golfe norte-coreano," saiu no  Nine News de Brisbane.

**Comment by arademaker** [comment]
I believe 1c6a2c6 solves everything reported here. For `norte-coreano`, I kept the compound analysis.

**Comment by vcvpaiva** [comment]
there's no reason to keep the compound for "norte-coreano". the Spanish and French PUDs use instead  "North Korea tournament", which bypasses the fact that in Portuguese we don't say "norte-coreano" but  we say instead "da Coreia do Norte" ou "coreano do norte".

this is a bad Anglicism.

**Comment by arademaker** [comment]
@vcvpaiva I didn't understand your argument. I believe versions 1 and 2 below are perfectly fine:

1. torneio de golfe norte-coreano
2. torneio de golfe da Corea do Norte
3. *torneio de golfe coreano do norte

What I would say invalid is 3.

Regarding the use of `compound`, we have some alternatives:

1. consider `norte-coreano` as a single word
2. *keep the `norte-coreano` multi-word and make `amod(torneio,norte)` and `amod(torneio,coreano)` both as ADJ 
3. keep the `norte-coreano` multi-word and make `amod(coreano,norte)` and `amod(torneio,coreano)`  both ADJ
3. keep the `norte-coreano` multi-word and make `compound(coreano,norte)` and `amod(torneio,coreano)`  both ADJ

I like the way it is now. But I am open to considering alternatives if we have arguments to change.

**Comment by vcvpaiva** [comment]
Spanish translation:
La jugarreta de la pareja les dio acceso al torneo de golf en Corea del Norte, informó la cadena Nine News de Brisbane.
Suggested Portuguese translation:
"Dupla faz pegadinha para entrar no torneio de golfe da Corea do Norte," noticiou o  Nine News de Brisbane.
or
"Dupla faz pegadinha para entrar no torneio de golfe norte-coreano," noticiou o  Nine News de Brisbane.
single-word, both work for me.
However "norte coreano" as a compound does not work for me.
