### ISSUE TITLE
GOP is masculine in Portuguese

### ISSUE THREAD

**Issue by vcvpaiva** [UniversalDependencies/UD_Portuguese-PUD#2]
sent_id = n01002017

text = Mas numa pausa da sua retórica passada acerca da restrição da imigração, o nomeado da GOP anunciou que, como presidente, ele iria permitir "números tremendos" de imigrantes legais, baseado num "sistema de mérito".

should be "o nomeado do GOP", as GOP = grand old party and party, "partido" is masculine in Portuguese

**Comment by vcvpaiva** [comment]
The translation in sent_id = n01002032 is totally wrong:


text = Então, eu odeio pôr um pouco de pressão em vocês, mas o destino dos republicanos está nos meus ombros, disse ele à multidão reunida num campo esportivo da Universidade de Carolina do Norte.

text_en = “So I hate to put a little pressure on you, but the fate of the republic rests on your shoulders,” he told the crowd gathered on a sports field at the University of North Carolina.

the fate is of the republic, not of republicans and  this fate rests on the audience's shoulders, not in the nominee's shoulders.

**Comment by arademaker** [comment]
comment https://github.com/UniversalDependencies/UD_Portuguese-PUD/issues/2#issuecomment-441303760 already reported in issue #3.
