### ISSUE TITLE
Common noun as proper

### ISSUE THREAD

**Issue by vcvpaiva** [UniversalDependencies/UD_Portuguese-PUD#21]
sent_id = n01003012
 text = O encontro foi originalmente marcado para o Clube Metropolitano Privado de Washington, na Rua H, a uns quarteirões de distância.
 text_en = The gathering was originally slated for Washington’s private Metropolitan Club on H Street a few blocks away.
Bad translation makes the fact that the Washington Club is a private club into part of its name.

O encontro foi originalmente marcado para o Clube Metropolitano, um club privado de Washington, na Rua H, a uns quarteirões de distância.

**Comment by arademaker** [comment]
The sentence mentions https://metroclub.com/About-The-Club, so I believe it would be better:

>  O encontro foi originalmente marcado para o Metropolitan Club, um club**e** privado de Washington, na Rua H, a uns quarteirões de distância.

ou ainda 

>  O encontro foi originalmente marcado para o privado Metropolitan Club de Washington, na Rua H, a uns quarteirões de distância.

**Comment by vcvpaiva** [comment]
whether you translate or not the name of the club is not important to me. (a bit like Pompey we translate, but calling Queen Elisabeth, Rainha Isabel II, only the European Portuguese do that!)
but the second translation above is not good Portuguese, in my opinion.

**Comment by arademaker** [comment]
commit 088aa44 solved it.
