### ISSUE TITLE
translation does not make sense

### ISSUE THREAD

**Issue by vcvpaiva** [UniversalDependencies/UD_Portuguese-PUD#22]
sent_id = n01064113
 text = Caplan descarta o voto retrospectivo, citando um par de estudiosos que o chamam "não mais racional do que matar o faraó quando o Nilo não inunda."
 text_en = Caplan dismisses retrospective voting, quoting a pair of scholars who call it “no more rational than killing the pharaoh when the Nile does not flood.”

a better (but still difficult to understand) translation
Caplan descarta o voto retrospectivo, citando um par de estudiosos que o chamam de "não mais racional do que matar o faraó quando o Nilo não inunda."
to avoid "garden-pathing" 
Caplan descarta o voto retrospectivo, citando um par de estudiosos que chamam esse voto de  "não mais racional do que matar o faraó quando o Nilo não inunda."

**Comment by arademaker** [comment]
The problem for me here is the analysis of `do que`. I am following here the Bosque analysis as a fixed expression. But I am not sure about it. Maybe @leoalenc can help!?

n01064113> Caplan descarta o voto retrospectivo, citando um par de estudiosos que o chamam "não mais racional do que matar o faraó quando o Nilo não inunda".

```
─┮  
 │ ╭─╼ Caplan PROPN nsubj 1 2  
 ╰─┾ descarta VERB root 2 0  
   │ ╭─╼ o DET det 3 4  
   ├─┾ voto NOUN obj 4 2  
   │ ╰─╼ retrospectivo ADJ amod 5 4  
   │ ╭─╼ , PUNCT punct 6 7  
   ├─┾ citando VERB advcl 7 2  
   │ │ ╭─╼ um DET det 8 9  
   │ ╰─┾ par NOUN obj 9 7  
   │   │ ╭─╼ de ADP case 10 11  
   │   ╰─┾ estudiosos NOUN nmod 11 9  
   │     │ ╭─╼ que PRON nsubj 12 14  
   │     │ ├─╼ o PRON obj 13 14  
   │     ╰─┾ chamam VERB acl 14 11  
   │       │ ╭─╼ " PUNCT punct 15 18  
   │       │ ├─╼ não ADV advmod 16 18  
   │       │ ├─╼ mais ADV advmod 17 18  
   │       ╰─┾ racional ADJ obj 18 14  
   │         │ ╭─┮ de ADP mark 19 22  
   │         │ │ ├─╼ o DET fixed 20 19  
   │         │ │ ╰─╼ que SCONJ fixed 21 19  
   │         ├─┾ matar VERB xcomp 22 18  
   │         │ │ ╭─╼ o DET det 23 24  
   │         │ ├─┶ faraó NOUN obj 24 22  
   │         │ │ ╭─╼ quando SCONJ mark 25 29  
   │         │ │ │ ╭─╼ o DET det 26 27  
   │         │ │ ├─┶ Nilo PROPN nsubj 27 29  
   │         │ │ ├─╼ não ADV advmod 28 29  
   │         │ ╰─┶ inunda VERB advcl 29 22  
   │         ╰─╼ " PUNCT punct 30 18  
   ╰─╼ . PUNCT punct 31 2  
```

**Comment by dan-zeman** [comment]
Couldn't _o_ be a pronoun and _que matar o faraó_ an adnominal phrase that modifies the pronoun?

**Comment by arademaker** [comment]
Hi @dan-zeman , are you thinking among these lines?

```
─┮  
 │ ╭─╼ Caplan PROPN nsubj 1 2  
 ╰─┾ descarta VERB root 2 0  
   │ ╭─╼ o DET det 3 4  
   ├─┾ voto NOUN obj 4 2  
   │ ╰─╼ retrospectivo ADJ amod 5 4  
   │ ╭─╼ , PUNCT punct 6 7  
   ├─┾ citando VERB advcl 7 2  
   │ │ ╭─╼ um DET det 8 9  
   │ ╰─┾ par NOUN obj 9 7  
   │   │ ╭─╼ de ADP case 10 11  
   │   ╰─┾ estudiosos NOUN nmod 11 9  
   │     │ ╭─╼ que PRON nsubj 12 14  
   │     │ ├─╼ o PRON obj 13 14  
   │     ╰─┾ chamam VERB acl 14 11  
   │       │ ╭─╼ " PUNCT punct 15 20  
   │       │ │ ╭─╼ não ADV advmod 16 18  
   │       │ │ ├─╼ mais ADV advmod 17 18  
   │       │ ├─┶ racional ADJ amod 18 20  
   │       │ ├─╼ de ADP case 19 20  
   │       ╰─┾ o PRON obj 20 14  
   │         │ ╭─╼ que ADP mark 21 22  
   │         ├─┾ matar VERB acl 22 20  
   │         │ │ ╭─╼ o DET det 23 24  
   │         │ ├─┶ faraó NOUN obj 24 22  
   │         │ │ ╭─╼ quando SCONJ mark 25 29  
   │         │ │ │ ╭─╼ o DET det 26 27  
   │         │ │ ├─┶ Nilo PROPN nsubj 27 29  
   │         │ │ ├─╼ não ADV advmod 28 29  
   │         │ ╰─┶ inunda VERB advcl 29 22  
   │         ╰─╼ " PUNCT punct 30 20  
   ╰─╼ . PUNCT punct 31 2  
```

**Comment by dan-zeman** [comment]
@arademaker : almost. But I would do:

xcomp(chamam, racional)
obl(racional, o)
case(o, de)
acl(o, matar)

**Comment by arademaker** [comment]
Hum, yes, it makes sense. 

```
─┮  
 │ ╭─╼ Caplan PROPN nsubj 1 2  
 ╰─┾ descarta VERB root 2 0  
   │ ╭─╼ o DET det 3 4  
   ├─┾ voto NOUN obj 4 2  
   │ ╰─╼ retrospectivo ADJ amod 5 4  
   │ ╭─╼ , PUNCT punct 6 7  
   ├─┾ citando VERB advcl 7 2  
   │ │ ╭─╼ um DET det 8 9  
   │ ╰─┾ par NOUN obj 9 7  
   │   │ ╭─╼ de ADP case 10 11  
   │   ╰─┾ estudiosos NOUN nmod 11 9  
   │     │ ╭─╼ que PRON nsubj 12 14  
   │     │ ├─╼ o PRON obj 13 14  
   │     ╰─┾ chamam VERB acl 14 11  
   │       │ ╭─╼ " PUNCT punct 15 18  
   │       │ ├─╼ não ADV advmod 16 18  
   │       │ ├─╼ mais ADV advmod 17 18  
   │       ╰─┾ racional ADJ xcomp 18 14  
   │         │ ╭─╼ de ADP case 19 20  
   │         ├─┾ o PRON obl 20 18  
   │         │ │ ╭─╼ que ADP mark 21 22  
   │         │ ╰─┾ matar VERB acl 22 20  
   │         │   │ ╭─╼ o DET det 23 24  
   │         │   ├─┶ faraó NOUN obj 24 22  
   │         │   │ ╭─╼ quando SCONJ mark 25 29  
   │         │   │ │ ╭─╼ o DET det 26 27  
   │         │   │ ├─┶ Nilo PROPN nsubj 27 29  
   │         │   │ ├─╼ não ADV advmod 28 29  
   │         │   ╰─┶ inunda VERB advcl 29 22  
   │         ╰─╼ " PUNCT punct 30 18  
   ╰─╼ . PUNCT punct 31 2  
```

**Comment by arademaker** [comment]
I know that @vcvpaiva asked to add an extra `de` in the translation:

> Caplan descarta o voto retrospectivo, citando um par de estudiosos que o chamam DE "não mais racional do que matar o faraó quando o Nilo não inunda."

But I really don't see it as necessary in Portuguese.

**Comment by vcvpaiva** [comment]
I disagree with the translation. "DE" seems to me necessary in the sentence. You don't say "Eles o chamam burro", nor "Eles o chamam charmoso". you need the "de" in these cases. 

also the translation using the "o voto" is much better than the one without it, as the English sentence is not ambiguous on whether who/what is being called is Caplan or the vote. While the Portuguese one suggested introduces this ambiguity and actually almost forces the interpretation that it's Caplan who's called, as votes are not usually "called" anything in Portuguese, let alone "no more rational than killing the pharaoh when the Nile does not flood.”

Can I reopen it, please?

Surely one should try to not introduce new ambiguities in the translated sentences.

**Comment by arademaker** [comment]
Hi, the problem here is the lack of guidelines for the translation. For me, the sentence is not ambiguous and the vote is the only possible candidate for being called `non-rational`... I feel less natural the `esse voto...` but I don't know how to resolve this conflict of points of view.

**Comment by dan-zeman** [comment]
I cannot provide an opinion on a translation into Portuguese. But if there are two native speakers with differing opinions, I would suggest to keep the variant that is closer to the translation originally provided by the translation company. (They are supposed to be professional translators, although we know that not all their output is perfect.)

**Comment by vcvpaiva** [comment]
>For me, the sentence is not ambiguous

What do you mean the sentence in PT is not ambiguous? "Caplan descarta o voto retrospectivo, citando um par de estudiosos que o chamam  CORNUDO" who's the "o" here?

so how do you know that  "o"  refers to the vote not Caplan?
In English we have "it" -- so it is clearly the vote.

but ok one sentence does not make much difference, in any case.

**Comment by arademaker** [comment]
I mean that `o` for me is clear the `vote`...
