### ISSUE TITLE
Barroso is a proper name

### ISSUE THREAD

**Issue by vcvpaiva** [UniversalDependencies/UD_Portuguese-PUD#23]
Barroso is not a common noun.

 newdoc id = n02068
 sent_id = n02068010
 text = A questão pode não ter acabado para Barroso.
 text_en = The issue might not be over for Barroso.
1	A	_	DET	DT	Gender=Fem|Number=Sing	2	det	_	_
2	questão	_	NOUN	NN	Gender=Fem|Number=Sing	6	nsubj	_	_
3	pode	_	VERB	VBC	Aspect=Imp|Mood=Ind|Number=Sing|Person=3|Tense=Pres	6	aux	_	_
4	não	_	ADV	RB	Polarity=Neg	6	advmod	_	_
5	ter	_	VERB	VB	_	6	aux	_	_
6	acabado	_	VERB	VBN	Aspect=Perf	0	root	_	_
7	para	_	ADP	IN	_	8	case	_	_
8	Barroso	_	NOUN	NN	Gender=Masc|Number=Sing	6	obl	_	Proper=True|SpaceAfter=No
9	.	_	PUNCT	.	_	6	punct	_	_

**Comment by arademaker** [comment]
already fixed.
