### ISSUE TITLE
minor: Mate 9 is a name

### ISSUE THREAD

**Issue by vcvpaiva** [UniversalDependencies/UD_Portuguese-PUD#24]
sent_id = n01016032
 text = Os telefones Mate 9 carecem de uma interface de inteligência artificial, como o Assistente do Google ou a Siri da Apple.
 text_en = The Mate 9 phones lack an artificial intelligence interface, like the Google Assistant or Apple's Siri.
1	Os	_	DET	DT	Gender=Masc|Number=Plur	2	det	_	_
2	telefones	_	NOUN	NN	Gender=Masc|Number=Plur	5	nsubj	_	_
3	**Mate	_	VERB	VBC	Aspect=Imp|Mood=Imp|Number=Sing|Person=3	2	appos	_	Proper=True**
4	9	_	NUM	CD	_	3	appos	_	Proper=True
5	carecem	_	VERB	VBC	Aspect=Imp|Mood=Ind|Number=Plur|Person=3|Tense=Pres	0	root	_	_
6	de	_	ADP	IN	_	8	case	_	_
7	uma	_	DET	DT	Gender=Fem|Number=Sing	8	det	_	_
8	interface	_	NOUN	NN	Gender=Fem|Number=Sing	5	obl	_	_
9	de	_	ADP	IN	_	10	case	_	_
10	inteligência	_	NOUN	NN	Gender=Fem|Number=Sing	8	nmod	_	_
11	artificial	_	ADJ	JJ	Gender=Fem|Number=Sing	10	amod	_	SpaceAfter=No
12	,	_	PUNCT	,	_	15	punct	_	_
13	como	_	ADP	IN	_	15	case	_	_
14	o	_	DET	DT	Gender=Masc|Number=Sing	15	det	_	_
15	Assistente	_	NOUN	NN	Gender=Masc|Number=Sing	5	obl	_	Proper=True
16-17	do	_	_	_	_	_	_	_	_
16	de	de	ADP	INDT	_	18	case	_	_
17	o	o	DET	_	Gender=Masc|Number=Sing	18	det	_	_
18	Google	_	PROPN	NNP	Gender=Masc|Number=Sing	15	nmod	_	_
19	ou	_	CCONJ	CC	_	21	cc	_	_
20	a	_	DET	DT	Gender=Fem|Number=Sing	21	det	_	_
21	Siri	_	NOUN	NN	Gender=Masc|Number=Sing	15	conj	_	Proper=True
22-23	da	_	_	_	_	_	_	_	_
22	de	de	ADP	INDT	_	24	case	_	_
23	a	o	DET	_	Gender=Fem|Number=Sing	24	det	_	_
24	Apple	_	PROPN	NNP	Gender=Fem|Number=Sing	21	nmod	_	SpaceAfter=No
25	.	_	PUNCT	.	_	5	punct	_	_

mate is the name, not a verb.

**Comment by arademaker** [comment]
fixed in 5d02a94
