### ISSUE TITLE
Bad translation: side should be "time"

### ISSUE THREAD

**Issue by vcvpaiva** [UniversalDependencies/UD_Portuguese-PUD#25]
newdoc id = n01073
 sent_id = n01073004
 text = Quem pode parar o lado da Austrália?
 text_en = Who can stop this Australia side?
1	Quem	_	PRON	WP	_	3	nsubj	_	_
2	pode	_	VERB	VBC	Aspect=Imp|Mood=Ind|Number=Sing|Person=3|Tense=Pres	3	aux	_	_
3	parar	_	VERB	VB	_	0	root	_	_
4	o	_	DET	DT	Gender=Masc|Number=Sing	5	det	_	_
5	lado	_	NOUN	NN	Gender=Masc|Number=Sing	3	obj	_	_
6-7	da	_	_	_	_	_	_	_	_
6	de	de	ADP	INDT	_	8	case	_	_
7	a	o	DET	_	Gender=Fem|Number=Sing	8	det	_	_
8	Austrália	_	PROPN	NNP	Gender=Fem|Number=Sing	5	nmod	_	SpaceAfter=No
9	?	_	PUNCT	.	_	3	punct	_	_

the translation should be:
Quem consegue segurar o time da Austrália?
ou 
Quem consegue parar o time da Austrália?
but no "lado", it makes no sense

**Comment by arademaker** [comment]
Why are you so confidant, without more context, about this error? Anyway, I changed the translation and fixed the analysis change token 2 to root and VERB. Token 3 is `xcomp` of token 2.

**Comment by vcvpaiva** [comment]
I am confident because Australia does NOT have sides! border perhaps, but one doesn't stop borders!

**Comment by arademaker** [comment]
But we can have an ellipse here... all about context. Imagine a previous sentence talking about two things I that could have sides ...  something like ...

> The stadium was crowded! Who can stop Australia's side?

**Comment by dan-zeman** [comment]
Here is the context: [The Guardian 2016-11-06](https://www.theguardian.com/sport/blog/2016/nov/06/mal-meningas-fearsome-freakish-australia-are-a-sight-to-behold).

The _side_ seems to mean a rugby team.

**Comment by arademaker** [comment]
For me the context gives more evidence that "side" works and could be translated as "lado"
