### ISSUE TITLE
alignment typo on code?

### ISSUE THREAD

**Issue by vcvpaiva** [UniversalDependencies/UD_Portuguese-PUD#27]
From raw looking at
sent_id = w01027015

the sentences below have nothing to do with each other.  As a result the CoNNLU of one sentence is totally repeated and one sentence is missing. The translation of the missing sentence should be something like:
Ele difere da porção oeste do país porque suas características topográficas proeminentes não são paralelas à costa.
It differs from the western portion of the country in that its prominent topographic features do not parallel the coast.

text = O norte da Argélia está na zona temperada e desfruta de um clima mediterrânico suave.
 text_en = It differs from the western portion of the country in that its prominent topographic features do not parallel the coast.
1	O	_	DET	DT	Gender=Masc|Number=Sing	2	det	_	_
2	norte	_	NOUN	NN	Gender=Masc|Number=Sing	6	nsubj	_	_
3-4	da	_	_	_	_	_	_	_	_
3	de	de	ADP	INDT	_	5	case	_	_
4	a	o	DET	_	Gender=Fem|Number=Sing	5	det	_	_
5	Argélia	_	PROPN	NNP	Gender=Fem|Number=Sing	2	nmod	_	_
6	está	_	VERB	VBC	Aspect=Imp|Mood=Ind|Number=Sing|Person=3|Tense=Pres	0	root	_	_
7-8	na	_	_	_	_	_	_	_	_
7	em	em	ADP	INDT	_	9	case	_	_
8	a	o	DET	_	Gender=Fem|Number=Sing	9	det	_	_
9	zona	_	NOUN	NN	Gender=Fem|Number=Sing	6	obl	_	_
10	temperada	_	ADJ	JJ	Gender=Fem|Number=Sing	9	amod	_	_
11	e	_	CCONJ	CC	_	12	cc	_	_
12	desfruta	_	VERB	VBC	Aspect=Imp|Mood=Ind|Number=Sing|Person=3|Tense=Pres	6	conj	_	_
13	de	_	ADP	IN	_	15	case	_	_
14	um	_	DET	DT	Gender=Masc|Number=Sing	15	det	_	_
15	clima	_	NOUN	NN	Gender=Masc|Number=Sing	12	obl	_	_
16	mediterrânico	_	ADJ	JJ	Gender=Masc|Number=Sing	15	amod	_	_
17	suave	_	ADJ	JJ	Gender=Masc|Number=Sing	15	amod	_	SpaceAfter=No
18	.	_	PUNCT	.	_	6	punct	_	_

**Comment by arademaker** [comment]
commit ad63da5 solved it.
