### ISSUE TITLE
very BAD translation: grade=ano escolar

### ISSUE THREAD

**Issue by vcvpaiva** [UniversalDependencies/UD_Portuguese-PUD#30]
sent_id = n01004017
text = Eles estão, na média nacional, na categoria 4 e, melhores que a média nacional, na categoria 8.
text_en = They are at the national average in grade 4 and better than national average in grade 8.

This is about "grade" as "year' in school (K-12), so it needs to be something like

Eles estão, na média nacional, no quarto ano e, melhores que a média nacional, no oitavo ano escolar.

**Comment by arademaker** [comment]
fixed in 42bb8cf.
