### ISSUE TITLE
BAD translation 

### ISSUE THREAD

**Issue by vcvpaiva** [UniversalDependencies/UD_Portuguese-PUD#31]
better translation:
Um indicador deste material meteorítico será provavelmente um elevado teor do elemento irídio
or
Um indicador deste material meteorítico será provavelmente (a existencia de) elevados  níveis do elemento irídio 

the difference is significative: the Portuguese sentence at the moment says that there is some something that is indicative of meteors, and that possibly has iridium.

while the English sentence says that *if* something has a meteoritic material this will likely have high levels of iridium.

sent_id = n01023043
 text = O indicador deste material meteorítico será provavelmente elevado em níveis do elemento irídio.
 text_en = A telltale of this meteoritic material will likely be high levels of the element iridium.
1	O	o	DET	DT	Gender=Masc|Number=Sing	2	det	_	_
2	indicador	indicador	NOUN	NN	Gender=Masc|Number=Sing	9	nsubj	_	_
3-4	deste	_	_	_	_	_	_	_	_
3	de	de	ADP	INDT	_	5	case	_	_
4	este	este	DET	_	Gender=Masc|Number=Sing	5	det	_	_
5	material	material	NOUN	NN	Gender=Masc|Number=Sing	2	nmod	_	_
6	meteorítico	_	ADJ	JJ	Gender=Masc|Number=Sing	5	amod	_	_
7	será	ser	AUX	VBC	Mood=Ind|Number=Sing|Person=3|Tense=Fut	9	cop	_	_
8	provavelmente	provavelmente	ADV	RB	_	9	advmod	_	_
9	elevado	elevado	ADJ	JJ	Gender=Masc|Number=Sing	0	root	_	_
10	em	em	ADP	IN	_	11	case	_	_
11	níveis	nível	NOUN	NN	Gender=Masc|Number=Plur	9	obl	_	_
12-13	do	_	_	_	_	_	_	_	_
12	de	de	ADP	INDT	_	14	case	_	_
13	o	o	DET	_	Gender=Masc|Number=Sing	14	det	_	_
14	elemento	elemento	NOUN	NN	Gender=Masc|Number=Sing	11	nmod	_	_
15	irídio	irídio	NOUN	NN	Gender=Masc|Number=Sing	14	appos	_	SpaceAfter=No
16	.	.	PUNCT	.	_	9	punct	_	_

**Comment by arademaker** [comment]
solved in fe7897c using 

> O indicador deste material meteorítico será provavelmente elevados níveis do elemento irídio.

**Comment by vcvpaiva** [comment]
I'm afraid still bad, the English sentence has "A telltale" this is "um [sinal]  indicativo". there's a big difference between "um sinal indicativo" e "o indicador".

**Comment by arademaker** [comment]
OK, changed the article.
