### ISSUE TITLE
question: cabelo na China?

### ISSUE THREAD

**Issue by vcvpaiva** [UniversalDependencies/UD_Portuguese-PUD#32]
sent_id = n01025040
 text = Na China, o cabelo é normalmente colocado num banho químico para remover por completo a cutícula, explica Tarlo.
text_en = In China the hair is typically put in a chemical bath to remove the cuticle completely, Tarlo explains.

The English root is "explains", the PT root is colocado/put. Parataxis is a difficult one, is the main clause "Tarlo explains" or what he explains=In China the hair is typically put in a chemical bath to remove the cuticle completel ?

**Comment by dan-zeman** [comment]
According to the [guidelines](https://universaldependencies.org/u/dep/parataxis.html#treatment-of-reported-speech) (example 10 therein), the annotation in English PUD is wrong. The root should be _put_, while _explains_ should be attached to it as `parataxis`.

(Personally I don't quite like this guideline. But that's how it stands :-))

**Comment by vcvpaiva** [comment]
many thanks, closing it.
