### ISSUE TITLE
more copula: white male identity

### ISSUE THREAD

**Issue by vcvpaiva** [UniversalDependencies/UD_Portuguese-PUD#33]
This seems a mistake in the PT annotation. EN says root is identity/identidade.
PT annotation says the root is "sido"=been

  sent_id = n01027030
 text = Grande parte do debate, do lado Democrático deste ano, tem sido sobre a identidade de homens brancos.
 text_en = Much of the debate, from the Democratic side this year, has been about white male identity.
1	Grande	grande	ADJ	JJ	Gender=Fem|Number=Sing	2	amod	_	_
2	parte	parte	NOUN	NN	Gender=Fem|Number=Sing	16	nsubj	_	_
3-4	do	_	_	_	_	_	_	_	_
3	de	de	ADP	INDT	_	5	case	_	_
4	o	o	DET	_	Gender=Masc|Number=Sing	5	det	_	_
5	debate	debate	NOUN	NN	Gender=Masc|Number=Sing	2	nmod	_	SpaceAfter=No
6	,	,	PUNCT	,	_	9	punct	_	_
7-8	do	_	_	_	_	_	_	_	_
7	de	de	ADP	INDT	_	9	case	_	_
8	o	o	DET	_	Gender=Masc|Number=Sing	9	det	_	_
9	lado	lado	NOUN	NN	Gender=Masc|Number=Sing	5	nmod	_	_
10	Democrático	democrático	ADJ	JJ	Gender=Masc|Number=Sing	9	amod	_	Proper=True
11-12	deste	_	_	_	_	_	_	_	_
11	de	de	ADP	INDT	_	13	case	_	_
12	este	este	DET	_	Gender=Masc|Number=Sing	13	det	_	_
13	ano	ano	NOUN	NN	Gender=Masc|Number=Sing	9	nmod	_	SpaceAfter=No
14	,	,	PUNCT	,	_	9	punct	_	_
15	tem	ter	AUX	VBC	Mood=Ind|Number=Sing|Person=3|Tense=Pres	16	aux	_	_
16	sido	_	VERB	VBN	_	0	root	_	_
17	sobre	_	ADP	IN	_	19	case	_	_
18	a	o	DET	DT	Gender=Fem|Number=Sing	19	det	_	_
19	identidade	identidade	NOUN	NN	Gender=Fem|Number=Sing	16	obl	_	_
20	de	de	ADP	IN	_	21	case	_	_
21	homens	homem	NOUN	NN	Gender=Masc|Number=Plur	19	nmod	_	_
22	brancos	branco	ADJ	JJ	Gender=Masc|Number=Plur	21	amod	_	SpaceAfter=No
23	.	.	PUNCT	.	_	16	punct	_	_

**Comment by dan-zeman** [comment]
Yes, _identidade_ should be the root, _tem_ should be attached to it as `aux` and _sido_ should be attached to the root as `cop`.

**Comment by vcvpaiva** [comment]
sorry, need to re-open! Verbs are ok now, but the meaning is not. 
The Portuguese sentence should be

>text = Grande parte do debate, do lado Democrático *neste* ano, tem sido sobre a identidade de homens brancos.

with "deste" we're saying that the year has a Democratic side and not that in this year, the Democratic side mostly did discuss white male identity.

**Comment by alvelvis** [comment]
I believe it's correct now

https://github.com/UniversalDependencies/UD_Portuguese-PUD/commit/72033755b868425f5c7f4ce907ddf3ae639273dd
