### ISSUE TITLE
bad translation plus wrong root for copula

### ISSUE THREAD

**Issue by vcvpaiva** [UniversalDependencies/UD_Portuguese-PUD#35]
(film) set=estúdio in Portuguese, not grupo=group.
better translation:
 text = Cuarón, cujo último filme foi o vencedor de Óscar Gravity, segundo as notícias, não estava no estúdio na hora do incidente.

root in EN is "set"=estúdio, root in PT is "estava"/was

sent_id = n01030006
 text = Cuarón, cujo último filme foi o vencedor de Óscar Gravity, segundo as notícias, não estava no grupo na hora do incidente.
 text_en = Cuaron, whose last film was the Oscar-winning Gravity, was reportedly not on set at the time of the incident.
1	Cuarón	Cuarón	PROPN	NNP	Gender=Masc|Number=Sing	18	nsubj	_	SpaceAfter=No
2	,	,	PUNCT	,	_	8	punct	_	_
3	cujo	_	PRON	WP	Gender=Masc|Number=Sing	5	amod	_	_
4	último	último	ADJ	JJ	Gender=Masc|Number=Sing	5	amod	_	_
5	filme	filme	NOUN	NN	Gender=Masc|Number=Sing	8	nsubj	_	_
6	foi	_	AUX	VBC	Mood=Ind|Number=Sing|Person=3|Tense=Past	8	cop	_	_
7	o	o	DET	DT	Gender=Masc|Number=Sing	8	det	_	_
8	vencedor	_	NOUN	NN	Gender=Masc|Number=Sing	1	acl:relcl	_	_
9	de	de	ADP	IN	_	10	case	_	_
10	Óscar	Óscar	PROPN	NNP	Gender=Masc|Number=Sing	8	nmod	_	ToDo=nmod
11	Gravity	Gravity	PROPN	NNP	Gender=Masc|Number=Sing	8	appos	_	SpaceAfter=No
12	,	,	PUNCT	,	_	15	punct	_	_
13	segundo	_	ADP	IN	_	15	case	_	_
14	as	o	DET	DT	Gender=Fem|Number=Plur	15	det	_	_
15	notícias	notícia	NOUN	NN	Gender=Fem|Number=Plur	18	obl	_	SpaceAfter=No
16	,	,	PUNCT	,	_	15	punct	_	_
17	não	não	ADV	RB	Polarity=Neg	18	advmod	_	_
18	estava	_	VERB	VBC	Mood=Ind|Number=Sing|Person=3|Tense=Past	0	root	_	_
19-20	no	_	_	_	_	_	_	_	_
19	em	em	ADP	INDT	_	21	case	_	_
20	o	o	DET	_	Gender=Masc|Number=Sing	21	det	_	_
21	grupo	grupo	NOUN	NN	Gender=Masc|Number=Sing	18	obl	_	_
22-23	na	_	_	_	_	_	_	_	_
22	em	em	ADP	INDT	_	24	case	_	_
23	a	o	DET	_	Gender=Fem|Number=Sing	24	det	_	_
24	hora	hora	NOUN	NN	Gender=Fem|Number=Sing	18	obl	_	_
25-26	do	_	_	_	_	_	_	_	_
25	de	de	ADP	INDT	_	27	case	_	_
26	o	o	DET	_	Gender=Masc|Number=Sing	27	det	_	_
27	incidente	incidente	NOUN	NN	Gender=Masc|Number=Sing	24	nmod	_	SpaceAfter=No
28	.	.	PUNCT	.	_	18	punct	_	_

**Comment by dan-zeman** [comment]
I fixed the copula annotation but I did not touch the translation.

**Comment by arademaker** [comment]
fixed the translation in 01f60b9.
