### ISSUE TITLE
questions on modal verbs: could/have to 

### ISSUE THREAD

**Issue by vcvpaiva** [UniversalDependencies/UD_Portuguese-PUD#36]
1. I believe we don't have the auxiliary modal verbs as roots.

 In English, the root is "find", not the modal "could". 
In Portuguese the root is "conseguiram"=managed=could. 

 sent_id = n01033021
 text = Contudo, eles não conseguiram encontrar esse mesmo padrão em tecidos como a bexiga, que não estão diretamente expostos.
 text_en = However, they could not find this same pattern in tissues such as the bladder, which are not directly exposed.

2. 
Another, perhaps similar, one:
 newdoc id = n01034
 sent_id = n01034033
 text = Se o Donald Trump se tornar presidente, o governo daqui ainda terá de trabalhar com ele para avançar com alguma agenda partilhada que exista, para garantir que os negócios e os interesses canadenses estão representados em Washington.
 text_en = "If Donald Trump becomes president, the government here will still have to work with him to advance whatever shared agenda there is, to ensure that Canadian businesses and interests are represented in Washington."

the root in English is "(have to) work", the root in Portuguese is work=trabalhar. It seems to me that the English is wrong in this case and "have to" should be an auxiliary, not the root.

**Comment by dan-zeman** [comment]
Not everything with a modal or near modal meaning is an auxiliary in UD. This can be observed also in English: _could_ is an auxiliary but _managed_ and _succeeded_ are not auxiliaries, hence if the English translation were _they did not manage to find..._, then _manage_ would be the root, and not _find_. So I think it is correct that the roots in English and Portuguese do not match and the Portuguese root is _conseguiram_.

The verb _have_ in English is auxiliary when it is used to create perfect and pluperfect tenses, as in _I have seen a bird._ It is not an auxiliary when used modally, as in _I have to go home_, although semantically similar _must_ and _should_ are auxiliaries. The language-specific tests whether a verb is auxiliary in a particular construction are primarily about grammatical behavior of the verb, less about its meaning. So I think the English PUD is right if it makes _work_ the root. The situation in Portuguese may or may not be the same, depending on what are the grammatical tests that show whether or not _ter_ is an auxiliary in this construction.

**Comment by vcvpaiva** [comment]
ok, thanks. closing the question.
