### ISSUE TITLE
bad translation: slow down=diminuir, not "diminuir lentamente"

### ISSUE THREAD

**Issue by vcvpaiva** [UniversalDependencies/UD_Portuguese-PUD#38]
sent_id = n01022010
 text = Estamos indo na direção certa: o Acordo de Paris vai lentamente diminuir as alterações climáticas, bem como a recente Emenda de Kigali vai reduzir os HFCs, disse Erik Solheim, chefe de Ambiente da UN.
 text_en = "We are moving in the right direction: the Paris Agreement will slow climate change, as will the recent Kigali Amendment to reduce HFCs," said Erik Solheim, head of UN Environment.

**Comment by arademaker** [comment]
commit a29e6bd solves it.

**Comment by arademaker** [comment]
My dictionary says `slow down` is better translated to `desacelerar`

**Comment by vcvpaiva** [comment]
there is no 'slow down' here. the English text is simply: the Paris Agreement will slow climate change [...]

**Comment by arademaker** [comment]
Oh, sorry, I was misled by the title of the issue. Anyway, don't you think that `desacelerar` still works fine?
