### ISSUE TITLE
verb ESTAR copula marked as full verb

### ISSUE THREAD

**Issue by vcvpaiva** [UniversalDependencies/UD_Portuguese-PUD#39]
several occurrences of ESTAR considered problematic.

1. the English version has no copula, but the verb "rests"
sent_id = n01002032
 text = Então, eu odeio pôr um pouco de pressão em vocês, mas o destino da república está nos seus ombros, disse ele à multidão reunida num campo esportivo da Universidade de Carolina do Norte.
 text_en = “So I hate to put a little pressure on you, but the fate of the republic rests on your shoulders,” he told the crowd gathered on a sports field at the University of North Carolina.
1	Então	então	ADV	RB	_	4	discourse	_	SpaceAfter=No
2	,	,	PUNCT	,	_	1	punct	_	_
3	eu	_	PRON	PRP	Case=Nom|Number=Sing|Person=1	4	nsubj	_	_
4	odeio	_	VERB	VBC	Mood=Ind|Number=Sing|Person=1|Tense=Pres	0	root	_	_
5	pôr	_	VERB	VB	_	4	xcomp	_	_
6	um	um	DET	DT	Gender=Masc|Number=Sing	7	det	_	_
7	pouco	pouco	NOUN	NN	Gender=Masc|Number=Sing	5	obj	_	_
8	de	de	ADP	IN	_	9	case	_	_
9	pressão	pressão	NOUN	NN	Gender=Fem|Number=Sing	7	nmod	_	_
10	em	em	ADP	IN	_	11	case	_	_
11	vocês	_	PRON	PRP	Number=Plur|Person=3	5	obl	_	SpaceAfter=No
12	,	,	PUNCT	,	_	13	punct	_	_
13	mas	_	CCONJ	CC	_	19	cc	_	_
14	o	o	DET	DT	Gender=Masc|Number=Sing	15	det	_	_
15	destino	destino	NOUN	NN	Gender=Masc|Number=Sing	19	nsubj	_	_
16-17	da	_	_	_	_	_	_	_	_
16	de	de	ADP	INDT	_	18	case	_	_
17	a	o	DET	_	Gender=Fem|Number=Sing	18	det	_	_
18	república	república	NOUN	NN	Gender=Fem|Number=Sing	15	nmod	_	_
19	está	estar	VERB	VBC	Mood=Ind|Number=Sing|Person=3|Tense=Pres	4	conj	_	_
20-21	nos	_	_	_	_	_	_	_	_
20	em	em	ADP	INDT	_	23	case	_	_
21	os	o	DET	_	Gender=Masc|Number=Plur	23	det	_	_
22	seus	seu	DET	DTP$	Gender=Masc|Number=Plur|PronType=Prs	23	det	_	_
23	ombros	ombro	NOUN	NN	Gender=Masc|Number=Plur	19	obl	_	SpaceAfter=No
24	,	,	PUNCT	,	_	25	punct	_	_
25	disse	dizer	VERB	VBC	Mood=Ind|Number=Sing|Person=3|Tense=Past	4	parataxis	_	_
26	ele	_	PRON	PRP	Case=Nom|Gender=Masc|Number=Sing|Person=3	25	nsubj	_	_
27-28	à	_	_	_	_	_	_	_	_
27	a	a	ADP	INDT	_	29	case	_	_
28	a	o	DET	_	Gender=Fem|Number=Sing	29	det	_	_
29	multidão	multidão	NOUN	NN	Gender=Fem|Number=Sing	25	obl	_	_
30	reunida	_	VERB	VBN	Gender=Fem|Number=Sing	29	acl	_	_
31-32	num	_	_	_	_	_	_	_	_
31	em	em	ADP	INDT	_	33	case	_	_
32	um	um	DET	_	Gender=Masc|Number=Sing	33	det	_	_
33	campo	campo	NOUN	NN	Gender=Masc|Number=Sing	30	obl	_	_
34	esportivo	esportivo	ADJ	JJ	Gender=Masc|Number=Sing	33	amod	_	_
35-36	da	_	_	_	_	_	_	_	_
35	de	de	ADP	INDT	_	37	case	_	_
36	a	o	DET	_	Gender=Fem|Number=Sing	37	det	_	_
37	Universidade	universidade	NOUN	NN	Gender=Fem|Number=Sing	33	nmod	_	Proper=True
38	de	de	ADP	IN	_	39	case	_	Proper=True
39	Carolina	Carolina	PROPN	NNP	Gender=Fem|Number=Sing	37	nmod	_	_
40-41	do	_	_	_	_	_	_	_	Proper=True
40	de	de	ADP	INDT	_	42	case	_	_
41	o	o	DET	_	Gender=Masc|Number=Sing	42	det	_	_
42	Norte	norte	NOUN	NN	Gender=Masc|Number=Sing	39	nmod	_	Proper=True|SpaceAfter=No
43	.	.	PUNCT	.	_	4	punct	_	_

2. "está" is copula not root.

newdoc id = n01068
 sent_id = n01068029
 text = O círculo eleitoral está na área do conselho de Kesteven do Norte, onde 62% dos eleitores apoiaram a saída da UE.
 text_en = The constituency is in the council area of North Kesteven, where 62% of voters backed leaving the EU.
1	O	o	DET	DT	Gender=Masc|Number=Sing	2	det	_	_
2	círculo	círculo	NOUN	NN	Gender=Masc|Number=Sing	4	nsubj	_	_
3	eleitoral	eleitoral	ADJ	JJ	Gender=Masc|Number=Sing	2	amod	_	_
4	está	estar	VERB	VBC	Mood=Ind|Number=Sing|Person=3|Tense=Pres	0	root	_	_
5-6	na	_	_	_	_	_	_	_	_
5	em	em	ADP	INDT	_	7	case	_	_
6	a	o	DET	_	Gender=Fem|Number=Sing	7	det	_	_
7	área	área	NOUN	NN	Gender=Fem|Number=Sing	4	obl	_	_
8-9	do	_	_	_	_	_	_	_	_
8	de	de	ADP	INDT	_	10	case	_	_
9	o	o	DET	_	Gender=Masc|Number=Sing	10	det	_	_
10	conselho	conselho	NOUN	NN	Gender=Masc|Number=Sing	7	nmod	_	_
11	de	de	ADP	IN	_	12	case	_	_
12	Kesteven	Kesteven	PROPN	NNP	Gender=Masc|Number=Sing	10	nmod	_	_
13-14	do	_	_	_	_	_	_	_	Proper=True
13	de	de	ADP	INDT	_	15	case	_	_
14	o	o	DET	_	Gender=Masc|Number=Sing	15	det	_	_
15	Norte	norte	NOUN	NN	Gender=Masc|Number=Sing	12	nmod	_	Proper=True|SpaceAfter=No
16	,	,	PUNCT	,	_	23	punct	_	_
17	onde	onde	ADV	WRB	_	23	advmod	_	_
18	62	_	NUM	CD	Gender=Masc	19	nummod	_	SpaceAfter=No
19	%	_	SYM	SYM	_	23	nsubj	_	_
20-21	dos	_	_	_	_	_	_	_	_
20	de	de	ADP	INDT	_	22	case	_	_
21	os	o	DET	_	Gender=Masc|Number=Plur	22	det	_	_
22	eleitores	eleitor	NOUN	NN	Gender=Masc|Number=Plur	19	nmod	_	ToDo=nmod
23	apoiaram	apoiar	VERB	VBC	Mood=Ind|Number=Plur|Person=3|Tense=Past	7	acl:relcl	_	_
24	a	o	DET	DT	Gender=Fem|Number=Sing	25	det	_	_
25	saída	saída	NOUN	NN	Gender=Fem|Number=Sing	23	obj	_	_
26-27	da	_	_	_	_	_	_	_	_
26	de	de	ADP	INDT	_	28	case	_	_
27	a	o	DET	_	Gender=Fem|Number=Sing	28	det	_	_
28	UE	UE	PROPN	NNP	Gender=Fem|Number=Sing	25	nmod	_	SpaceAfter=No
29	.	.	PUNCT	.	_	4	punct	_	_

**Comment by vcvpaiva** [comment]
3.
 sent_id = n01074015
 text = A África do Sul está quase em um beco sem saída e nós temos que conseguir alcançar suas expectativas.
 text_en = South Africa are almost at the point of no return and we have to be able to match their desire.
1	A	o	DET	DT	Gender=Fem|Number=Sing	2	det	_	_
2	África	África	PROPN	NNP	Gender=Fem|Number=Sing	6	nsubj	_	_
3-4	do	_	_	_	_	_	_	_	Proper=True
3	de	de	ADP	INDT	_	5	case	_	_
4	o	o	DET	_	Gender=Masc|Number=Sing	5	det	_	_
5	Sul	sul	NOUN	NN	Gender=Masc|Number=Sing	2	nmod	_	Proper=True
6	está	estar	VERB	VBC	Mood=Ind|Number=Sing|Person=3|Tense=Pres	0	root	_	_
7	quase	quase	ADV	RB	_	6	advmod	_	_
8	em	em	ADP	IN	_	10	case	_	_
9	um	um	DET	DT	Gender=Masc|Number=Sing	10	det	_	_
10	beco	beco	NOUN	NN	Gender=Masc|Number=Sing	6	obl	_	_
11	sem	_	ADP	IN	_	12	case	_	_
12	saída	saída	NOUN	NN	Gender=Fem|Number=Sing	10	nmod	_	_
13	e	e	CCONJ	CC	_	17	cc	_	_
14	nós	_	PRON	PRP	Case=Nom|Number=Plur|Person=1	17	nsubj	_	_
15	temos	ter	AUX	VBC	Mood=Ind|Number=Plur|Person=1|Tense=Pres	17	aux	_	_
16	que	_	ADP	IN	_	15	fixed	_	_
17	conseguir	_	VERB	VB	_	6	conj	_	_
18	alcançar	_	VERB	VB	_	17	xcomp	_	_
19	suas	_	PRON	DTP$	Gender=Fem|Number=Plur|Number[psor]=Sing|Person=3|PronType=Prs	20	det	_	_
20	expectativas	expectativa	NOUN	NN	Gender=Fem|Number=Plur	18	obj	_	SpaceAfter=No
21	.	.	PUNCT	.	_	6	punct	_	_

**Comment by vcvpaiva** [comment]
4.
 newdoc id = n01079
 sent_id = n01079015
 text = No canto, está uma menina com um lenço na cabeça e calça jeans, com um ar tão modesto que penso ser outra assistente.
 text_en = In the corner is a girl in a headscarf and jeans who looks so unassuming I think it’s another assistant.
1-2	No	_	_	_	_	_	_	_	_
1	Em	em	ADP	INDT	_	3	case	_	_
2	o	o	DET	_	Gender=Masc|Number=Sing	3	det	_	_
3	canto	canto	NOUN	NN	Gender=Masc|Number=Sing	5	obl	_	SpaceAfter=No
4	,	,	PUNCT	,	_	3	punct	_	_
5	está	estar	VERB	VBC	Mood=Ind|Number=Sing|Person=3|Tense=Pres	0	root	_	_
6	uma	um	DET	DT	Gender=Fem|Number=Sing	7	det	_	_
7	menina	menino	NOUN	NN	Gender=Fem|Number=Sing	5	nsubj	_	_
8	com	_	ADP	IN	_	10	case	_	_
9	um	um	DET	DT	Gender=Masc|Number=Sing	10	det	_	_
10	lenço	lenço	NOUN	NN	Gender=Masc|Number=Sing	7	nmod	_	_
11-12	na	_	_	_	_	_	_	_	_
11	em	em	ADP	INDT	_	13	case	_	_
12	a	o	DET	_	Gender=Fem|Number=Sing	13	det	_	_
13	cabeça	cabeça	NOUN	NN	Gender=Fem|Number=Sing	10	nmod	_	_
14	e	e	CCONJ	CC	_	15	cc	_	_
15	calça	calça	NOUN	NN	Gender=Fem|Number=Sing	10	conj	_	_
16	jeans	jeans	ADJ	JJ	Gender=Fem|Number=Sing	15	amod	_	SpaceAfter=No
17	,	,	PUNCT	,	_	20	punct	_	_

**Comment by vcvpaiva** [comment]
5. 
 sent_id = n01105013
 text = Mas agora tudo está fora de questão e ele parece estar à procura de respostas a toda hora.
 text_en = But right now everything is out of kilter and he seems to be seeking answers all the time.
1	Mas	_	CCONJ	CC	_	4	discourse	_	_
2	agora	agora	ADV	RB	_	4	advmod	_	_
3	tudo	_	NOUN	NN	Gender=Masc|Number=Sing	4	nsubj	_	_
4	está	estar	VERB	VBC	Mood=Ind|Number=Sing|Person=3|Tense=Pres	0	root	_	_
5	fora	fora	ADV	RB	_	4	advmod	_	_
6	de	de	ADP	IN	_	7	case	_	_
7	questão	questão	NOUN	NN	Gender=Fem|Number=Sing	5	obl	_	_
8	e	e	CCONJ	CC	_	10	cc	_	_
9	ele	_	PRON	PRP	Case=Nom|Gender=Masc|Number=Sing|Person=3	10	nsubj	_	_
10	parece	parecer	VERB	VBC	Mood=Ind|Number=Sing|Person=3|Tense=Pres	4	conj	_	_
11	estar	_	VERB	VB	_	10	xcomp	_	_
12-13	à	_	_	_	_	_	_	_	_
12	a	a	ADP	INDT	_	14	case	_	_
13	a	o	DET	_	Gender=Fem|Number=Sing	14	det	_	_
14	procura	procura	NOUN	NN	Gender=Fem|Number=Sing	11	obl	_	_
15	de	de	ADP	IN	_	16	case	_	_
16	respostas	resposta	NOUN	NN	Gender=Fem|Number=Plur	14	nmod	_	_
17	a	_	ADP	IN	_	19	case	_	_
18	toda	_	DET	DT	Gender=Fem|Number=Sing	19	det	_	_
19	hora	hora	NOUN	NN	Gender=Fem|Number=Sing	10	obl	_	SpaceAfter=No
20	.	.	PUNCT	.	_	4	punct	_	_

**Comment by vcvpaiva** [comment]
6.
 sent_id = w01027035
 text = O norte da Argélia está na zona temperada e goza de um clima mediterrânico suave.
 text_en = Northern Algeria is in the temperate zone and enjoys a mild, Mediterranean climate.
1	O	o	DET	DT	Gender=Masc|Number=Sing	2	det	_	_
2	norte	norte	NOUN	NN	Gender=Masc|Number=Sing	6	nsubj	_	_
3-4	da	_	_	_	_	_	_	_	_
3	de	de	ADP	INDT	_	5	case	_	_
4	a	o	DET	_	Gender=Fem|Number=Sing	5	det	_	_
5	Argélia	Argélia	PROPN	NNP	Gender=Fem|Number=Sing	2	nmod	_	_
6	está	estar	VERB	VBC	Mood=Ind|Number=Sing|Person=3|Tense=Pres	0	root	_	_
7-8	na	_	_	_	_	_	_	_	_
7	em	em	ADP	INDT	_	9	case	_	_
8	a	o	DET	_	Gender=Fem|Number=Sing	9	det	_	_
9	zona	zona	NOUN	NN	Gender=Fem|Number=Sing	6	obl	_	_
10	temperada	temperado	ADJ	JJ	Gender=Fem|Number=Sing	9	amod	_	_
11	e	e	CCONJ	CC	_	12	cc	_	_
12	goza	gozar	VERB	VBC	Mood=Ind|Number=Sing|Person=3|Tense=Pres	6	conj	_	_
13	de	de	ADP	IN	_	15	case	_	_
14	um	um	DET	DT	Gender=Masc|Number=Sing	15	det	_	_
15	clima	clima	NOUN	NN	Gender=Masc|Number=Sing	12	obl	_	_
16	mediterrânico	mediterrânico	ADJ	JJ	Gender=Masc|Number=Sing	15	amod	_	_
17	suave	suave	ADJ	JJ	Gender=Masc|Number=Sing	15	amod	_	SpaceAfter=No
18	.	.	PUNCT	.	_	6	punct	_	_

**Comment by vcvpaiva** [comment]
7.
 newdoc id = w01041
 sent_id = w01041046
 text = No entanto, na Tailândia, a urbanização também esteve na origem de aumentos maciços de problemas como a obesidade.
\# text_en = However, in Thailand, urbanization has also resulted in massive increases in problems such as obesity.
1-2	No	_	_	_	_	_	_	_	_
1	Em	em	ADP	INDT	_	12	discourse	_	_
2	o	o	DET	_	Gender=Masc|Number=Sing	1	fixed	_	_
3	entanto	_	NOUN	NN	Gender=Masc|Number=Sing	1	fixed	_	SpaceAfter=No
4	,	,	PUNCT	,	_	1	punct	_	_
5-6	na	_	_	_	_	_	_	_	_
5	em	em	ADP	INDT	_	7	case	_	_
6	a	o	DET	_	Gender=Fem|Number=Sing	7	det	_	_
7	Tailândia	Tailândia	PROPN	NNP	Gender=Fem|Number=Sing	12	obl	_	SpaceAfter=No
8	,	,	PUNCT	,	_	7	punct	_	_
9	a	o	DET	DT	Gender=Fem|Number=Sing	10	det	_	_
10	urbanização	urbanização	NOUN	NN	Gender=Fem|Number=Sing	12	nsubj	_	_
11	também	também	ADV	RB	_	12	advmod	_	_
12	esteve	estar	VERB	VBC	Mood=Ind|Number=Sing|Person=3|Tense=Past	0	root	_	_
13-14	na	_	_	_	_	_	_	_	_
13	em	em	ADP	INDT	_	15	case	_	_
14	a	o	DET	_	Gender=Fem|Number=Sing	15	det	_	_
15	origem	origem	NOUN	NN	Gender=Fem|Number=Sing	12	obl	_	_
16	de	de	ADP	IN	_	17	case	_	_
17	aumentos	aumento	NOUN	NN	Gender=Masc|Number=Plur	15	nmod	_	_
18	maciços	maciço	ADJ	JJ	Gender=Masc|Number=Plur	17	amod	_	_
19	de	de	ADP	IN	_	20	case	_	_
20	problemas	problema	NOUN	NN	Gender=Masc|Number=Plur	17	nmod	_	_
21	como	como	ADP	IN	_	23	case	_	_
22	a	o	DET	DT	Gender=Fem|Number=Sing	23	det	_	_
23	obesidade	obesidade	NOUN	NN	Gender=Fem|Number=Sing	20	nmod	_	SpaceAfter=No
24	.	.	PUNCT	.	_	12	punct	_	_

**Comment by vcvpaiva** [comment]
8. missing quotes too:
 newdoc id = n03008
 sent_id = n03008011
 text = ETA está de saída, o contigente Francês revelou.
 text_en = "ETA is on its way out," the French contingent revealed.
1	ETA	ETA	PROPN	NNP	Gender=Masc|Number=Sing	2	nsubj	_	_
2	está	estar	VERB	VBC	Mood=Ind|Number=Sing|Person=3|Tense=Pres	0	root	_	_
3	de	de	ADP	IN	_	4	case	_	_
4	saída	saída	NOUN	NN	Gender=Fem|Number=Sing	2	obl	_	SpaceAfter=No
5	,	,	PUNCT	,	_	9	punct	_	_
6	o	o	DET	DT	Gender=Masc|Number=Sing	7	det	_	_
7	contigente	_	NOUN	NN	Gender=Masc|Number=Sing	9	nsubj	_	_
8	Francês	francês	ADJ	JJ	Gender=Masc|Number=Sing	7	amod	_	_
9	revelou	revelar	VERB	VBC	Mood=Ind|Number=Sing|Person=3|Tense=Past	2	parataxis	_	SpaceAfter=No
10	.	.	PUNCT	.	_	2	punct	_	_

**Comment by dan-zeman** [comment]
Fixed _estar_ in all eight sentences, closing the issue. The missing quotes perhaps belong to another issue.

**Comment by vcvpaiva** [comment]
thanks!

**Comment by arademaker** [comment]
For n01002032 I would prefer having `disse` as root and the whole discourse being cited as dependent of the verb disse (say)...  but I will consider this issue closed.

**Comment by dan-zeman** [comment]
If it's just about personal preferences, I'd prefer that too, but it would be against the guidelines, specifically the example 10 [here](https://universaldependencies.org/u/dep/parataxis.html#treatment-of-reported-speech).

**Comment by arademaker** [comment]
Wow! In Bosque, I am adopting the ccomp analysis in general... More work to be done.
