### ISSUE TITLE
"estavam" as copula

### ISSUE THREAD

**Issue by vcvpaiva** [UniversalDependencies/UD_Portuguese-PUD#43]
1. 
 sent_id = w02008055
 text = Eles estavam principalmente em montanhas.
 text_en = They were primarily on hills.
1	Eles	_	PRON	PRP	Case=Nom|Gender=Masc|Number=Plur|Person=3	2	nsubj	_	_
2	estavam	_	VERB	VBC	Aspect=Imp|Mood=Ind|Number=Plur|Person=3|Tense=Past	0	root	_	_
3	principalmente	_	ADV	RB	_	5	advmod	_	ToDo=ex-adp-child
4	em	_	ADP	IN	_	5	case	_	_
5	montanhas	_	NOUN	NN	Gender=Fem|Number=Plur	2	obl	_	SpaceAfter=No
6	.	_	PUNCT	.	_	2	punct	_	_

**Comment by vcvpaiva** [comment]
2.
 sent_id = w02017061
 text = Os traços de sangue no pano estavam no formato que foram reportados pelo relatório de notícias no dia do assassinato.
 text_en = The traces of blood on the clothes were in the shape that they were reported to have by the news reports on the day of the murder.
1	Os	_	DET	DT	Gender=Masc|Number=Plur	2	det	_	_
2	traços	_	NOUN	NN	Gender=Masc|Number=Plur	8	nsubj	_	_
3	de	_	ADP	IN	_	4	case	_	_
4	sangue	_	NOUN	NN	Gender=Masc|Number=Sing	2	nmod	_	_
5-6	no	_	_	_	_	_	_	_	_
5	em	em	ADP	INDT	_	7	case	_	_
6	o	o	DET	_	Gender=Masc|Number=Sing	7	det	_	_
7	pano	_	NOUN	NN	Gender=Masc|Number=Sing	2	nmod	_	_
8	estavam	_	VERB	VBC	Aspect=Imp|Mood=Ind|Number=Plur|Person=3|Tense=Past	0	root	_	_
9-10	no	_	_	_	_	_	_	_	_
9	em	em	ADP	INDT	_	11	case	_	_
10	o	o	DET	_	Gender=Masc|Number=Sing	11	det	_	_
11	formato	_	NOUN	NN	Gender=Masc|Number=Sing	8	obl	_	_
12	que	_	PRON	WP	_	14	obj	_	ToDo=pobj
13	foram	_	VERB	VBC	Aspect=Perf|Mood=Ind|Number=Plur|Person=3|Tense=Past	14	aux:pass	_	_
14	reportados	_	VERB	VBN	Aspect=Perf|Gender=Masc|Number=Plur	11	acl:relcl	_	_
15-16	pelo	_	_	_	_	_	_	_	_
15	por	por	ADP	INDT	_	17	case	_	_
16	o	o	DET	_	Gender=Masc|Number=Sing	17	det	_	_
17	relatório	_	NOUN	NN	Gender=Masc|Number=Sing	14	obl	_	_
18	de	_	ADP	IN	_	19	case	_	_
19	notícias	_	NOUN	NN	Gender=Fem|Number=Plur	17	nmod	_	_
20-21	no	_	_	_	_	_	_	_	_
20	em	em	ADP	INDT	_	22	case	_	_
21	o	o	DET	_	Gender=Masc|Number=Sing	22	det	_	_
22	dia	_	NOUN	NN	Gender=Masc|Number=Sing	14	obl	_	_
23-24	do	_	_	_	_	_	_	_	_
23	de	de	ADP	INDT	_	25	case	_	_
24	o	o	DET	_	Gender=Masc|Number=Sing	25	det	_	_
25	assassinato	_	NOUN	NN	Gender=Masc|Number=Sing	22	nmod	_	SpaceAfter=No
26	.	_	PUNCT	.	_	8	punct	_	_

**Comment by arademaker** [comment]
commit 399e023 solved this issue.
