### ISSUE TITLE
Particles in Portuguese

### ISSUE THREAD

**Issue by vcvpaiva** [UniversalDependencies/UD_Portuguese-PUD#44]
PUD-EN is not consistent with prefixes:

1. "anti-fascist" is not broken down in
 _text_en = Tina Anselmi was born on the 25th of March, 1927 in Castelfranco Veneto; she grew up in an anti-fascist Catholic family, which was marked by the persecution of her militant socialist father._

but
2. "post-classic" in 
 _text_en = During the Post-Classic period in Yucatán a third system was in use._
 is transformed into a compound:

3	Post	Post	NOUN	NN	Number=Sing	5	compound	5:compound	SpaceAfter=No
4	-	-	PUNCT	HYPH	_	5	punct	5:punct	SpaceAfter=No
5	Classic	Classic	ADJ	JJ	Degree=Pos	6	amod	6:amod	Proper=True

I was expecting the same analysis in both cases.

3. This is relevant to the title of the issue, as the only "particles" in the Bosque corpus are

_anti, pré, pós_

which are not considered "particles" in English, even if the words are basically the same.

Should these be particles, because lexica downstream needs to look up the main part?
Or should they be considered a single hyphenated word?

**Comment by dan-zeman** [comment]
If they are written with a hyphen and without spaces, it would be easier to treat them as one word.

**Comment by vcvpaiva** [comment]
Yes, they're written with a hyphen and without spaces as in:

1.  text = Tina Anselmi nasceu em 25 de março, 1927 em Castelfranco Veneto; ela cresceu em uma família católica **anti-fascista,** a qual foi marcada por perseguições ao seu pai militante socialista.
2. text = Durante o período **pós-clássico** em Iucatão, um terceiro sistema estava em uso.

so they are not 'particles', correct?

**Comment by dan-zeman** [comment]
Yes. They are prefixes. Sometimes a prefix occurs alone and then it may be difficult to find a POS tag for it. But here the prefixes are just a part of the adjective.

**Comment by vcvpaiva** [comment]
thanks, closing the issue
