### ISSUE TITLE
many validation errors

### ISSUE THREAD

**Issue by arademaker** [UniversalDependencies/UD_Portuguese-PUD#8]
```
% cat pt_pud-ud-test.conllu|  python3 ../ud-tools/validate.py --lang pt
[Line 101 Sent n01002017 Node 11]: [L3 Syntax leaf-fixed] 'fixed' not expected to have children (11:de:fixed --> 12:a:det)
[Line 121 Sent n01002017 Node 30]: [L3 Syntax rel-upos-aux] 'aux' should be 'AUX' but it is 'VERB'
[Line 201 Sent n01002042 Node 4]: [L3 Syntax rel-upos-aux] 'aux' should be 'AUX' but it is 'VERB'
[Line 219 Sent n01002058 Node 4]: [L3 Syntax rel-upos-aux] 'aux' should be 'AUX' but it is 'VERB'
[Line 225 Sent n01002058 Node 10]: [L3 Syntax rel-upos-aux] 'aux' should be 'AUX' but it is 'VERB'
[Line 308 Sent n01003012 Node 3]: [L3 Syntax rel-upos-aux] 'aux' should be 'AUX' but it is 'VERB'
[Line 357 Sent n01004009 Node 10]: [L3 Syntax rel-upos-aux] 'aux' should be 'AUX' but it is 'VERB'
[Line 449 Sent n01005024 Node 11]: [L3 Syntax rel-upos-aux] 'aux' should be 'AUX' but it is 'VERB'
[Line 476 Sent n01005031 Node 9]: [L3 Syntax rel-upos-aux] 'aux' should be 'AUX' but it is 'VERB'
[Line 505 Sent n01006011 Node 10]: [L3 Syntax rel-upos-aux] 'aux' should be 'AUX' but it is 'VERB'
[Line 537 Sent n01008017 Node 3]: [L3 Syntax rel-upos-aux] 'aux' should be 'AUX' but it is 'VERB'
[Line 546 Sent n01008017 Node 9]: [L3 Syntax leaf-fixed] 'fixed' not expected to have children (9:de:fixed --> 10:os:det)
[Line 558 Sent n01008017 Node 21]: [L3 Syntax rel-upos-aux] 'aux' should be 'AUX' but it is 'VERB'
[Line 583 Sent n01008017 Node 44]: [L3 Syntax rel-upos-aux] 'aux' should be 'AUX' but it is 'VERB'
[Line 600 Sent n01009027 Node 6]: [L3 Syntax rel-upos-aux] 'aux' should be 'AUX' but it is 'VERB'
[Line 663 Sent n01010042 Node 15]: [L3 Syntax rel-upos-aux] 'aux' should be 'AUX' but it is 'VERB'
[Line 674 Sent n01011004 Node 2]: [L3 Syntax rel-upos-aux] 'aux' should be 'AUX' but it is 'VERB'
[Line 678 Sent n01011004 Node 6]: [L3 Syntax rel-upos-aux] 'aux' should be 'AUX' but it is 'VERB'
[Line 753 Sent n01011017 Node 12]: [L3 Syntax rel-upos-aux] 'aux' should be 'AUX' but it is 'VERB'
...suppressing further errors regarding Syntax
Syntax errors: 618
*** FAILED *** with 618 errors
```

**Comment by dan-zeman** [comment]
Fixing `[L3 Syntax rel-upos-aux]` was easy and it brought the number of errors down by some 500. Here is the new report:

<pre>
[Line 101 Sent n01002017 Node 11]: [L3 Syntax leaf-fixed] 'fixed' not expected to have children (11:de:fixed --> 12:a:det)
[Line 546 Sent n01008017 Node 9]: [L3 Syntax leaf-fixed] 'fixed' not expected to have children (9:de:fixed --> 10:os:det)
[Line 941 Sent n01015036 Node 31]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'NOUN'
[Line 1234 Sent n01019005 Node 9]: [L3 Syntax leaf-fixed] 'fixed' not expected to have children (9:de:fixed --> 10:a:det)
[Line 1352 Sent n01021007 Node 5]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'NOUN'
[Line 1898 Sent n01025045 Node 4]: [L3 Syntax leaf-fixed] 'fixed' not expected to have children (4:de:fixed --> 5:a:det)
[Line 2111 Sent n01029007 Node 3]: [L3 Syntax right-to-left-appos] Relation 'appos' must go left-to-right.
[Line 2622 Sent n01035004 Node 2]: [L3 Syntax leaf-fixed] 'fixed' not expected to have children (2:de:fixed --> 3:o:det)
[Line 2883 Sent n01037020 Node 16]: [L3 Syntax leaf-fixed] 'fixed' not expected to have children (16:de:fixed --> 17:o:det)
[Line 3298 Sent n01043005 Node 35]: [L3 Syntax rel-upos-case] 'case' should not be 'NUM'
[Line 5280 Sent n01070017 Node 7]: [L3 Syntax leaf-fixed] 'fixed' not expected to have children (7:de:fixed --> 8:a:det)
[Line 5685 Sent n01076030 Node 5]: [L3 Syntax leaf-fixed] 'fixed' not expected to have children (5:de:fixed --> 6:a:det)
[Line 5807 Sent n01079065 Node 15]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'PRON'
[Line 6193 Sent n01085008 Node 10]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'NOUN'
[Line 6868 Sent n01095004 Node 17]: [L3 Syntax leaf-fixed] 'fixed' not expected to have children (17:de:fixed --> 18:a:det)
[Line 7116 Sent n01098044 Node 20]: [L3 Syntax leaf-fixed] 'fixed' not expected to have children (20:de:fixed --> 21:o:det)
[Line 7385 Sent n01104011 Node 17]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'NOUN'
[Line 7686 Sent n01108003 Node 21]: [L3 Syntax leaf-fixed] 'fixed' not expected to have children (21:de:fixed --> 22:isso:det)
[Line 8169 Sent n01114025 Node 9]: [L3 Syntax leaf-fixed] 'fixed' not expected to have children (9:a:fixed --> 10:o:det)
[Line 8636 Sent n01121032 Node 13]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'PRON'
[Line 10840 Sent w01004051 Node 11]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'NOUN'
[Line 10933 Sent w01005022 Node 7]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'NOUN'
[Line 10985 Sent w01005024 Node 2]: [L3 Syntax leaf-fixed] 'fixed' not expected to have children (2:de:fixed --> 3:isso:det)
[Line 11302 Sent w01010044 Node 29]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'NOUN'
[Line 11356 Sent w01010046 Node 3]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'NOUN'
[Line 11438 Sent w01012052 Node 2]: [L3 Syntax leaf-fixed] 'fixed' not expected to have children (2:de:fixed --> 3:isso:det)
[Line 11613 Sent w01016028 Node 10]: [L3 Syntax rel-upos-det] 'det' should be 'DET' or 'PRON' but it is 'ADJ'
[Line 12046 Sent w01020017 Node 36]: [L3 Syntax leaf-fixed] 'fixed' not expected to have children (36:de:fixed --> 37:os:det)
[Line 12056 Sent w01020018 Node 2]: [L3 Syntax leaf-fixed] 'fixed' not expected to have children (2:a:fixed --> 3:o:det)
[Line 12264 Sent w01023120 Node 1]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'NOUN'
[Line 12273 Sent w01023120 Node 10]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'NOUN'
[Line 12754 Sent w01029083 Node 15]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'NOUN'
[Line 13007 Sent w01031015 Node 9]: [L3 Syntax leaf-fixed] 'fixed' not expected to have children (9:a:fixed --> 10:o:det)
[Line 13017 Sent w01031015 Node 20]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'NOUN'
[Line 13113 Sent w01033067 Node 9]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'NOUN'
[Line 13255 Sent w01035082 Node 4]: [L3 Syntax leaf-fixed] 'fixed' not expected to have children (4:de:fixed --> 5:os:det)
[Line 13284 Sent w01035082 Node 31]: [L3 Syntax leaf-fixed] 'fixed' not expected to have children (31:de:fixed --> 32:a:det)
[Line 13347 Sent w01036044 Node 18]: [L3 Syntax leaf-fixed] 'fixed' not expected to have children (18:a:fixed --> 19:a:det)
[Line 13446 Sent w01038009 Node 7]: [L3 Syntax leaf-fixed] 'fixed' not expected to have children (7:a:fixed --> 8:as:det)
[Line 13897 Sent w01043065 Node 21]: [L3 Syntax leaf-fixed] 'fixed' not expected to have children (21:de:fixed --> 22:a:det)
[Line 14071 Sent w01045005 Node 3]: [L3 Syntax leaf-fixed] 'fixed' not expected to have children (3:de:fixed --> 4:o:det)
[Line 14269 Sent w01047008 Node 21]: [L3 Syntax leaf-fixed] 'fixed' not expected to have children (21:de:fixed --> 22:o:det)
[Line 15052 Sent w01056103 Node 32]: [L3 Syntax leaf-fixed] 'fixed' not expected to have children (32:de:fixed --> 33:o:det)
[Line 15130 Sent w01057041 Node 26]: [L3 Syntax leaf-fixed] 'fixed' not expected to have children (26:de:fixed --> 27:a:det)
[Line 15384 Sent w01062037 Node 14]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'NOUN'
[Line 15487 Sent w01064034 Node 7]: [L3 Syntax leaf-fixed] 'fixed' not expected to have children (7:de:fixed --> 8:a:det)
[Line 15587 Sent w01065019 Node 33]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'NOUN'
[Line 15665 Sent w01065022 Node 13]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'NOUN'
[Line 15852 Sent w01067032 Node 2]: [L3 Syntax leaf-fixed] 'fixed' not expected to have children (2:de:fixed --> 3:isso:det)
[Line 15916 Sent w01067103 Node 2]: [L3 Syntax leaf-fixed] 'fixed' not expected to have children (2:de:fixed --> 3:isto:det)
[Line 15983 Sent w01068056 Node 5]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'NOUN'
[Line 16028 Sent w01069040 Node 4]: [L3 Syntax leaf-fixed] 'fixed' not expected to have children (4:de:fixed --> 5:as:det)
[Line 16142 Sent w01070031 Node 16]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'NOUN'
[Line 16156 Sent w01070031 Node 30]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'NOUN'
[Line 16518 Sent w01073067 Node 9]: [L3 Syntax rel-upos-nummod] 'nummod' should be 'NUM' but it is 'CCONJ'
[Line 16545 Sent w01073075 Node 7]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'NOUN'
[Line 16605 Sent w01075036 Node 14]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'ADP'
[Line 16725 Sent w01075038 Node 28]: [L3 Syntax rel-upos-det] 'det' should be 'DET' or 'PRON' but it is 'ADP'
[Line 16796 Sent w01075040 Node 3]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'ADP'
[Line 17475 Sent w01086012 Node 14]: [L3 Syntax leaf-fixed] 'fixed' not expected to have children (14:de:fixed --> 15:a:det)
[Line 17566 Sent w01088099 Node 21]: [L3 Syntax leaf-mark-case] 'case' not expected to have children (21:em:case --> 24:diz:acl)
[Line 17892 Sent w01095089 Node 6]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'NOUN'
[Line 18049 Sent w01095093 Node 16]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'NOUN'
[Line 18329 Sent w01100046 Node 7]: [L3 Syntax leaf-aux-cop] 'aux' not expected to have children (7:encontrava:aux --> 6:se:compound)
[Line 18552 Sent w01101084 Node 1]: [L3 Syntax leaf-aux-cop] 'aux' not expected to have children (1:Foram:aux --> 3:lhe:iobj)
[Line 19999 Sent w01125034 Node 8]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'NOUN'
[Line 20634 Sent w01132081 Node 18]: [L3 Syntax leaf-fixed] 'fixed' not expected to have children (18:de:fixed --> 19:isso:det)
[Line 20739 Sent w01134009 Node 2]: [L3 Syntax leaf-fixed] 'fixed' not expected to have children (2:de:fixed --> 3:a:det)
[Line 22050 Sent w01150046 Node 3]: [L3 Syntax leaf-fixed] 'fixed' not expected to have children (3:de:fixed --> 4:isso:det)
[Line 22952 Sent n02046037 Node 6]: [L3 Syntax rel-upos-case] 'case' should not be 'PRON'
[Line 23292 Sent n02075020 Node 11]: [L3 Syntax leaf-fixed] 'fixed' not expected to have children (11:a:fixed --> 12:os:det)
[Line 24197 Sent n03010012 Node 15]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'ADP'
[Line 24827 Sent n04010016 Node 2]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'NOUN'
[Line 25069 Sent n05002023 Node 2]: [L3 Syntax leaf-fixed] 'fixed' not expected to have children (2:de:fixed --> 3:isso:det)
[Line 25132 Sent n05003019 Node 3]: [L3 Syntax leaf-fixed] 'fixed' not expected to have children (3:eles:fixed --> 2:de:case)
[Line 25226 Sent n05005002 Node 4]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'NOUN'
[Line 25258 Sent n05005016 Node 7]: [L3 Syntax leaf-fixed] 'fixed' not expected to have children (7:a:fixed --> 8:o:det)
[Line 26018 Sent w02007032 Node 24]: [L3 Syntax leaf-fixed] 'fixed' not expected to have children (24:de:fixed --> 25:a:det)
[Line 26137 Sent w02008028 Node 23]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'NOUN'
[Line 26172 Sent w02008038 Node 28]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'NOUN'
[Line 26190 Sent w02008065 Node 2]: [L3 Syntax leaf-fixed] 'fixed' not expected to have children (2:de:fixed --> 3:isso:det)
[Line 26292 Sent w02009087 Node 14]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'NOUN'
[Line 26823 Sent w02019085 Node 26]: [L3 Syntax leaf-fixed] 'fixed' not expected to have children (26:a:fixed --> 27:os:det)
[Line 26991 Sent w03003039 Node 21]: [L3 Syntax rel-upos-nummod] 'nummod' should be 'NUM' but it is 'CCONJ'
[Line 27068 Sent w03005012 Node 5]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'NOUN'
[Line 27133 Sent w03005014 Node 3]: [L3 Syntax leaf-fixed] 'fixed' not expected to have children (3:de:fixed --> 4:o:det)
[Line 27136 Sent w03005014 Node 7]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'NOUN'
[Line 27202 Sent w03005016 Node 6]: [L3 Syntax leaf-fixed] 'fixed' not expected to have children (6:de:fixed --> 4:aproximadamente:obj)
[Line 27206 Sent w03005016 Node 6]: [L3 Syntax leaf-fixed] 'fixed' not expected to have children (6:de:fixed --> 7:o:det)
[Line 27209 Sent w03005016 Node 10]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'NOUN'
[Line 27269 Sent w03007008 Node 11]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'NOUN'
[Line 27287 Sent w03007039 Node 5]: [L3 Syntax leaf-fixed] 'fixed' not expected to have children (5:de:fixed --> 6:o:det)
[Line 27639 Sent w04001037 Node 2]: [L3 Syntax leaf-fixed] 'fixed' not expected to have children (2:de:fixed --> 3:isso:det)
[Line 28227 Sent w04010027 Node 2]: [L3 Syntax right-to-left-appos] Relation 'appos' must go left-to-right.
[Line 28432 Sent w05001045 Node 12]: [L3 Syntax leaf-fixed] 'fixed' not expected to have children (12:de:fixed --> 13:o:det)
[Line 28485 Sent w05002032 Node 5]: [L3 Syntax rel-upos-cop] 'cop' should be 'AUX' or 'PRON'/'DET' but it is 'ADP'
[Line 28486 Sent w05002032 Node 5]: [L3 Syntax leaf-aux-cop] 'cop' not expected to have children (5:a:cop --> 6:o:det)
[Line 28485 Sent w05002032 Node 9]: [L3 Syntax leaf-mark-case] 'case' not expected to have children (9:Andes:case --> 5:a:cop)
[Line 28487 Sent w05002032 Node 9]: [L3 Syntax leaf-mark-case] 'case' not expected to have children (9:Andes:case --> 7:chamado:amod)
[Line 28498 Sent w05002032 Node 9]: [L3 Syntax leaf-mark-case] 'case' not expected to have children (9:Andes:case --> 18:formados:acl)
[Line 28485 Sent w05002032 Node 5]: [L5 Syntax cop-lemma] 'a' is not a copula in language [pt]
[Line 29212 Sent w05010027 Node 7]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'NOUN'
Syntax errors: 102
*** FAILED *** with 102 errors</pre>

**Comment by arademaker** [comment]
Thank you. Can you report how you fixed them?

**Comment by arademaker** [comment]
I suppose a simple replacement, of all tokens with deprel=aux was changed from UPOSTAG=VERB to UPOSTAG=AUX, right?

**Comment by arademaker** [comment]
The only problem is that we have too many suspicious auxiliary verbs ...

**Comment by dan-zeman** [comment]
Yes:
<pre>
udapy -s util.Eval node='if node.upos=="VERB" and (node.deprel=="aux" or node.deprel=="aux:pass"): node.upos="AUX"' < backup.conllu > pt_pud-ud-test.conllu
</pre>

I agree that the list of auxiliary verbs in Portuguese seems suspiciously long. If there are additional unlisted auxiliaries in PUD, the validator won't report them until PUD has lemmas. Nevertheless, no information was lost by the current partial fix, as the `aux` and `aux:pass` deprels were already there.

**Comment by arademaker** [comment]
Sure, I will work on adding lemmas using the same approach I did for the GSD corpus.

**Comment by arademaker** [comment]
Latter, @dan-zeman , I would like to explore your work on http://ufal.mff.cuni.cz/deep-universal-dependencies... but this is not the best channel to talk about it! ;-)

**Comment by vcvpaiva** [comment]
> The only problem is that we have too many suspicious auxiliary verbs ...

I don't think so!
 looking at stats for PUD-EN and PUD-PT, PT has a third of the aux of EN. this doesn't make sense, every aux in EN should correspond to an aux in PT and we traditionally have more (some wrong, I agree) auxiliaries. this needs investigation. 

as does the fact that stats say PT has NO subordinate conjunctions, which is crazy, as EN has 290 of them!

**Comment by dan-zeman** [comment]
<pre>
Fri Oct  9 17:27:00 CEST 2020
tools/check_files.pl UD_Portuguese-PUD
[L0 Repo lang-spec-doc] UD_Portuguese-PUD: Language 'pt' does not have the one-page documentation summary in the docs repository (the file exists but it seems incomplete).
See http://universaldependencies.org/contributing_language_specific.html for instructions on how to write documentation.
*** FAILED ***
./validate.sh --lang pt --max-err 0 UD_Portuguese-PUD/pt_pud-ud-test.conllu
[Line 941 Sent n01015036 Node 31]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'NOUN'
[Line 1352 Sent n01021007 Node 5]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'NOUN'
[Line 5807 Sent n01079065 Node 15]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'PRON'
[Line 6193 Sent n01085008 Node 10]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'NOUN'
[Line 7385 Sent n01104011 Node 17]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'NOUN'
[Line 8636 Sent n01121032 Node 13]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'PRON'
[Line 10840 Sent w01004051 Node 11]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'NOUN'
[Line 10933 Sent w01005022 Node 7]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'NOUN'
[Line 11302 Sent w01010044 Node 29]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'NOUN'
[Line 11356 Sent w01010046 Node 3]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'NOUN'
[Line 12264 Sent w01023120 Node 1]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'NOUN'
[Line 12273 Sent w01023120 Node 10]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'NOUN'
[Line 12754 Sent w01029083 Node 15]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'NOUN'
[Line 13017 Sent w01031015 Node 20]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'NOUN'
[Line 13113 Sent w01033067 Node 9]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'NOUN'
[Line 15384 Sent w01062037 Node 14]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'NOUN'
[Line 15587 Sent w01065019 Node 33]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'NOUN'
[Line 15665 Sent w01065022 Node 13]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'NOUN'
[Line 15983 Sent w01068056 Node 5]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'NOUN'
[Line 16142 Sent w01070031 Node 16]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'NOUN'
[Line 16156 Sent w01070031 Node 30]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'NOUN'
[Line 16545 Sent w01073075 Node 7]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'NOUN'
[Line 17892 Sent w01095089 Node 6]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'NOUN'
[Line 18049 Sent w01095093 Node 16]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'NOUN'
[Line 18329 Sent w01100046 Node 7]: [L3 Syntax leaf-aux-cop] 'aux' not expected to have children (7:encontrava:aux --> 6:se:compound)
[Line 18552 Sent w01101084 Node 1]: [L3 Syntax leaf-aux-cop] 'aux' not expected to have children (1:Foram:aux --> 3:lhe:iobj)
[Line 19999 Sent w01125034 Node 8]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'NOUN'
[Line 24827 Sent n04010016 Node 2]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'NOUN'
[Line 25226 Sent n05005002 Node 4]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'NOUN'
[Line 26137 Sent w02008028 Node 23]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'NOUN'
[Line 26172 Sent w02008038 Node 28]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'NOUN'
[Line 26292 Sent w02009087 Node 14]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'NOUN'
[Line 27068 Sent w03005012 Node 5]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'NOUN'
[Line 27136 Sent w03005014 Node 7]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'NOUN'
[Line 27209 Sent w03005016 Node 10]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'NOUN'
[Line 27269 Sent w03007008 Node 11]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'NOUN'
[Line 29212 Sent w05010027 Node 7]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'NOUN'
Syntax errors: 37
*** FAILED *** with 37 errors
</pre>

**Comment by vcvpaiva** [comment]
I am investigating aux's as I expected a similar number in both languages. By and large things like
would allow<==>iria permitir 
are ok as there's one aux in EN, and one in PT.

there are some excessive use of auxiliary verbs like in the example above
[Line 18329 Sent w01100046 Node 7]: [L3 Syntax leaf-aux-cop] 'aux' not expected to have children (7:encontrava:aux --> 6:se:compound)
the verb "encontrar" (to meet) should not be AUX.

but numbers as they stand (328 AUX in PT) versus (1014 AUX in EN) seem very strange to me

it seems to me that one of the problems is lack of AUX in places like:
 sent_id = n01002058
 text = O que ele está dizendo e o que ela está fazendo, na verdade, é inacreditável.
text_en = What she’s saying and what she’s doing, it — actually, it’s unbelievable.
...
4	está	_	VERB	VBC	Aspect=Imp|Mood=Ind|Number=Sing|Person=3|Tense=Pres	5	aux	_	_
5	dizendo	_	VERB	VBG	Aspect=Imp	1	acl:relcl	_	_
where aux is at the end but not at the beginning. is that what you corrected?

**Comment by vcvpaiva** [comment]
Portuguese, like Spanish and French has two versions of the verb "to be" (SER and ESTAR).
 I think ESTAR is not being considered an auxililary verb, when it is one.
hence the line
4 está _ VERB VBC Aspect=Imp|Mood=Ind|Number=Sing|Person=3|Tense=Pres 5 aux _ _
above

**Comment by dan-zeman** [comment]
If you were looking at `stats.xml` you were not getting the up-to-date picture; there are 844 instances of `AUX` at present. I corrected `VERB` --> `AUX` but I did not bother updating `stats.xml` because it will be updated automatically at release time. (Nevertheless, I updated it now.)

**Comment by vcvpaiva** [comment]
many thanks! yes, this was what I was calling for.
844 is much better than 328, assuming the PUD-EN is correct.
and yes, I  hoped that was what you'd corrected, but wanted to be sure.
